careusers/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = "careusers"

urlpatterns = [

    #以下はアクセス制限はviewsにて
    path("list/",login_required(views.CareuserListView.as_view()),name="list"),
    path("list/edit/<int:pk>/",login_required(views.CareuserEditView.as_view()),name="edit"),
    path("list/new/",login_required(views.CareuserCreateView.as_view()),name="new"),

    path("def_schedule/edit/<int:pk>/",login_required(views.DefscheduleEditView.as_view()),name="def_sche_edit"),
    path("def_schedule/new/<int:careuser_id>",login_required(views.DefscheduleCreateView.as_view()),name="def_sche_new"),
    path("def_schedule/delete/<int:pk>/",login_required(views.DefscheduleDeleteView.as_view()),name="def_sche_delete"),
]

hana/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from django.http import HttpResponse


urlpatterns = [
    #staffs.admin.pyのadmin.site.register(User, MyUserAdmin)もコメントアウト済み
    #path("ad_ksg/", admin.site.urls),
    path("staff/",include("staffs.urls")), 
    path("careuser/",include("careusers.urls")),
    path("service/",include("services.urls")),
    path("schedule/",include("schedules.urls")),
    path("aggregate/",include("aggregates.urls")),
    path("pdf/",include("pdfgen.urls")),
    url(r'^robots.txt$', lambda r: HttpResponse("User-agent: *\nDisallow: /", content_type="text/plain")),
]

schedules/urls.py
from django.urls import register_converter,path
from . import path_converter
from . import views,scheduleimportviews
from django.contrib.auth.decorators import login_required

app_name = "schedules"

register_converter(path_converter.FourDigitYearConverter,'yyyy')
register_converter(path_converter.TweDigitMonthConverter,'mm')
register_converter(path_converter.TweDigitDayConverter,'dd')

urlpatterns = [

    #ログイン済みの場合のみ
    path("day/",login_required(views.ScheduleDailyListView.as_view()),name="todaylist"),
    path("daily/<yyyy:year>/<mm:month>/<dd:day>",login_required(views.ScheduleDailyListView.as_view()), name='dailylist'),
    path("calender/",login_required(views.ScheduleCalendarListView.as_view()), name='calendar'),
    path("monthlycalender/<yyyy:year>/<mm:month>",login_required(views.ScheduleCalendarListView.as_view()), name="monthlycalendar"),
    path("report/<int:pk>/",login_required(views.ReportUpdateView.as_view()),name="report"),
    path("report/detail/<int:pk>/",login_required(views.ReportDetailView.as_view()),name="report_detail"),
    path("report_before/<int:careuser>/<int:page>/",login_required(views.ReportBeforeListView.as_view()),name="report_before"),
    path("add_request/",login_required(views.AddRequestView.as_view()),name="add_request"),

    #以下はstaffuserのみアクセス可能(viewsにて制限)
    path("month/",login_required(views.ScheduleListView.as_view()),name="thismonthlist"),
    path("monthly/<yyyy:year>/<mm:month>",login_required(views.ScheduleListView.as_view()),name="monthlylist"),
    path("monthly/<yyyy:year>/<mm:month>/<dd:day>",login_required(views.ScheduleListView.as_view()),name="dayselectlist"),
    path("import/",login_required(scheduleimportviews.ScheduleImportView.as_view()),name="import"),
    path("import_next/",login_required(scheduleimportviews.ScheduleImportView.as_view()),name="import_next"),
    path("edit/<int:pk>/",login_required(views.ScheduleEditView.as_view()),name="edit"),
    path("new/",login_required(views.ScheduleCreateView.as_view()),name="new"),
    path("delete/<int:pk>/",login_required(views.ScheduleDeleteView.as_view()),name="delete"),
    path("showstaff/<yyyy:year>/<mm:month>",login_required(views.ScheduleShowStaffView.as_view()),name="monthly_show_allstaff"),
    path("confirmed_addrequest/<int:pk>/",login_required(views.ConfirmedAddRequestView.as_view()),name="confirmed_add_request"),
    path("manage/",login_required(views.ManageTopView.as_view()),name="manage_top_thismonth"),
    path("manage/<yyyy:year>/<mm:month>",login_required(views.ManageTopView.as_view()),name="manage_top_monthly"),
    path("manage_monthly_check/<yyyy:year>/<mm:month>",login_required(views.ManageMonthlyCheckListView.as_view()),name="manage_monthly_check"),
]

careusers/models.py
from services.models import Service
from django.db import models
from staffs.models import User
import datetime
from django.utils import timezone
from django.core.validators import RegexValidator,MinValueValidator,MaxValueValidator

class CareUser(models.Model):

    gender_choice =[(0,"男"),(1,"女"),]
  
    last_name      = models.CharField(verbose_name="姓",max_length=30)
    first_name     = models.CharField(verbose_name="名",max_length=30)
    short_name     = models.CharField(verbose_name="短縮名",max_length=30,default="",blank=True)
    last_kana      = models.CharField(verbose_name="せい",max_length=30)
    first_kana     = models.CharField(verbose_name="めい",max_length=30)
    gender         = models.PositiveSmallIntegerField(verbose_name="性別",default=0,choices=gender_choice)
    birthday       = models.DateField(verbose_name="生年月日",blank=True)
    report_send    = models.BooleanField(verbose_name="サービス実施記録メール送信",default=False)
    report_email   = models.EmailField(verbose_name="サービス実施記録送信先メールアドレス",blank=True,null=True,unique=True)
    user_no        = models.PositiveSmallIntegerField(verbose_name="利用者番号",blank=True, null=True,unique=True)
    postcode       = models.CharField(verbose_name="郵便番号",max_length=7)
    adr_ken        = models.CharField(verbose_name="都道府県",max_length=4)
    adr_siku       = models.CharField(verbose_name="市区町村",max_length=30)
    adr_tyou       = models.CharField(verbose_name="町名・番地",max_length=30)
    adr_bld        = models.CharField(verbose_name="ビル・マンション名",max_length=40,default="",blank=True)
    tel            = models.CharField(verbose_name="電話番号",max_length=15,default="",blank=True)
    phone          = models.CharField(verbose_name="携帯",max_length=15,default="",blank=True)
    startdate      = models.DateField(verbose_name="契約日",blank=True,null=True)
    biko           = models.TextField(verbose_name="備考",default="",blank=True)
    is_active      = models.BooleanField(verbose_name="利用中",default=True)
    no_active_date = models.DateField(verbose_name="利用終了日時",blank=True,null=True)

    def __str__(self):
        return f"{self.last_name}　{self.first_name}"
    
    def get_short_name(self):
        if self.short_name == None or self.short_name=="":
            s_name = self.last_name
        else:
            s_name = self.short_name
        return s_name
    
    def is_birthday(self):
        #誕生日判定
        birthday_flg = False
        now = datetime.datetime.now()
        now = timezone.make_aware(now)
        if self.birthday:
            if self.birthday.month == now.month and self.birthday.day == now.day:
                birthday_flg=True
        return birthday_flg



class DefaultSchedule(models.Model):

    type_choice = [(0,"週ベース"),(1,"日ベース")]
    weektype_choice = [(0,"毎週"),(1,"隔週1-3-5"),(2,"隔週2-4"),(3,"第1"),(4,"第2"),(5,"第3"),(6,"第4"),(7,"第5")]
    daytype_choice  = [(0,"毎日"),(1,"奇数日"),(2,"偶数日"),(3,"日付指定")]
    peoples_choice = [(1,"1名"),(2,"2名"),(3,"3名"),(4,"4名")]

    day_regex  = [MinValueValidator(0), MaxValueValidator(31)]
    hour_regex = [MinValueValidator(0), MaxValueValidator(23)]
    min_regex  = [MinValueValidator(0), MaxValueValidator(59)]

    careuser = models.ForeignKey(CareUser,verbose_name="利用者名",on_delete=models.CASCADE)
    type     = models.PositiveSmallIntegerField(verbose_name="",default=0,choices=type_choice)
    weektype = models.PositiveSmallIntegerField(verbose_name="週指定",default=0,choices=weektype_choice)
    sun      = models.BooleanField(verbose_name="日",default=False)
    mon      = models.BooleanField(verbose_name="月",default=False)
    tue      = models.BooleanField(verbose_name="火",default=False)
    wed      = models.BooleanField(verbose_name="水",default=False)
    thu      = models.BooleanField(verbose_name="木",default=False)
    fri      = models.BooleanField(verbose_name="金",default=False)
    sat      = models.BooleanField(verbose_name="土",default=False)
    daytype  = models.PositiveSmallIntegerField(verbose_name="日指定",default=0,choices=daytype_choice)
    day      = models.PositiveSmallIntegerField(verbose_name="日付",validators=day_regex,blank=True, null=True)
    biko     = models.TextField(verbose_name="備考",default="",blank=True)
    
    start_h  = models.PositiveSmallIntegerField(verbose_name="開始時",validators=hour_regex)
    start_m  = models.PositiveSmallIntegerField(verbose_name="開始分",validators=min_regex)
    service  = models.ForeignKey(Service,verbose_name="利用サービス",on_delete=models.RESTRICT)
    peoples  = models.PositiveSmallIntegerField(verbose_name="必要人数",default=1,choices=peoples_choice)
    add_stop   = models.BooleanField(verbose_name="予定を自動追加しない",default=False)
    no_set_staff   = models.BooleanField(verbose_name="スタッフを自動入力しない",default=False)

    def __str__(self):
        return f"{self.careuser}" 

    def get_schedule_name(self):
        name_type  = ""
        name_param = ""
        #サイクル表示
        if self.type == 0:
            name_type = self.get_weektype_display()
            if self.sun == True:
                name_param += " 日"
            if self.mon == True:
                name_param += " 月"
            if self.tue == True:
                name_param += " 火"
            if self.wed == True:
                name_param += " 水"
            if self.thu == True:
                name_param += " 木"
            if self.fri == True:
                name_param += " 金"
            if self.sat == True:
                name_param += " 土"
        elif self.type == 1:
            if self.daytype != 3:
                name_type = self.get_daytype_display()
            else:
                name_type  = "毎月"
                name_param = str(self.day) + "日"

        sche_name = name_type + " " + name_param + " "

        return sche_name

    def get_start_time(self):
        name_time  = ""
        #時間表示
        if self.start_h != "" and self.start_h != None and self.start_m != "" and self.start_m != None :
            name_time  = str(self.start_h).zfill(2) + ":" + str(self.start_m).zfill(2) + " ~ "
        else:
            name_time = ""
            
        return name_time

    def get_end_time(self):
        endtime = ""
        if self.get_start_time() != "":
            start   = datetime.time(self.start_h,self.start_m)
            endtime = datetime.datetime.combine(datetime.date.today(), start) + datetime.timedelta(minutes = self.service.time)
            endtime = endtime.strftime("%H:%M")
        
        return f"{endtime}"
    

careusers/forms.py
from .models import CareUser,DefaultSchedule,User,Service
from django import forms
import datetime
from django.db.models import Case, When, Value,PositiveSmallIntegerField

class CareUserForm(forms.ModelForm):
    class Meta:
        model = CareUser
        fields = '__all__'
        year = int(datetime.datetime.now().strftime('%Y'))+1
        widgets = {
            'birthday': forms.SelectDateWidget(years=[x for x in range(1910,year)]),
            'startdate': forms.SelectDateWidget(years=[x for x in range(year-15,year)])
        }

class DefscheduleForm(forms.ModelForm):
    class Meta:
        model = DefaultSchedule
        exclude =  ('careuser',)

    def __init__ (self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        odr_text = Case(
            When(title__startswith="身体", then=Value(0)),
            When(title__startswith="生活", then=Value(1)),
            When(title__startswith="家事", then=Value(2)),
            When(title__startswith="重度", then=Value(3)),
            When(title__startswith="通院",title__icontains="身有", then=Value(4)),
            When(title__startswith="通院",title__icontains="身無", then=Value(5)),
            When(title__icontains="身有", then=Value(6)),
            When(title__icontains="身無", then=Value(7)),
            default=Value(9),
            output_field=PositiveSmallIntegerField()
        )
        self.fields['service'].queryset = Service.objects.annotate(odr_text=odr_text).filter(is_active=True).order_by('kind','odr_text','time')

class DefscheduleNewForm(forms.ModelForm):
    class Meta:
        model = DefaultSchedule
        fields = '__all__'
        widgets = {
            'careuser': forms.HiddenInput()
        }
    
    def __init__ (self, careuser=None, *args, **kwargs):
        if careuser != None:
            self.base_fields["careuser"].initial = careuser
        super().__init__(*args, **kwargs)
        odr_text = Case(
            When(title__startswith="身体", then=Value(0)),
            When(title__startswith="生活", then=Value(1)),
            When(title__startswith="家事", then=Value(2)),
            When(title__startswith="重度", then=Value(3)),
            When(title__startswith="通院",title__icontains="身有", then=Value(4)),
            When(title__startswith="通院",title__icontains="身無", then=Value(5)),
            When(title__icontains="身有", then=Value(6)),
            When(title__icontains="身無", then=Value(7)),
            default=Value(9),
            output_field=PositiveSmallIntegerField()
        )
        self.fields['service'].queryset = Service.objects.annotate(odr_text=odr_text).filter(is_active=True).order_by('kind','odr_text','time')

templates/careusers/careuser_form.html
{% extends "staffs/base.html" %}
{% load static %}
{% load django_bootstrap5 %}
{% load crispy_forms_tags %}
{% load crispy_forms_field %}
{% block extraheader %}
    <link rel="stylesheet" href="{% static 'css/careuser_form.css' %}?1">
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'js/careuser_form.js' %}?1"></script>
{% endblock %}
{% block main %}
<div class="container">
    <h4 class="my-5">利用者登録</h4>
    <div class="my-5"><a href="{% url 'careusers:list' %}">{% bootstrap_button button_type="button" content="　戻　る　" %}</a></div>
    <form method="post">
        {% csrf_token %}
        <div class="row gx-1">
            <div class="col-2">{{ form.last_name | as_crispy_field }}</div>
            <div class="col-2">{{ form.first_name | as_crispy_field }}</div>
        </div>
        <div class="row gx-1">
            <div class="col-2">{{ form.last_kana | as_crispy_field }}</div>
            <div class="col-2">{{ form.first_kana | as_crispy_field }}</div>
        </div>
        <div class="col-2">{{ form.short_name | as_crispy_field }}</div>
        <div class="col-2">{{ form.gender | as_crispy_field }}</div>
        <div class="col-5">{{ form.birthday | as_crispy_field }}</div>
        <div class="col-2">{{ form.postcode | as_crispy_field }}</div>
        <div class="row gx-1">
            <div class="col-2">{{ form.adr_ken | as_crispy_field }}</div>
            <div class="col-4">{{ form.adr_siku | as_crispy_field }}</div>
        </div>
        <div class="col-4">{{ form.adr_tyou | as_crispy_field }}</div>
        <div class="col-4">{{ form.adr_bld | as_crispy_field }}</div>
        <div class="col-2">{{ form.tel | as_crispy_field }}</div>
        <div class="col-2">{{ form.phone | as_crispy_field }}</div>
        <div class="col-2">{{ form.report_send | as_crispy_field }}</div>
        <div class="col-4">{{ form.report_email | as_crispy_field }}</div>
        <div class="col-5">{{ form.startdate | as_crispy_field }}</div>
        <div class="col-6">{{ form.biko | as_crispy_field }}</div>
        <div class="col-1">{{ form.is_active | as_crispy_field }}</div>
        <div class="col-3">{{ form.no_active_date | as_crispy_field }}</div>
        <div class="col-3">{% bootstrap_button button_type="submit" size="lg" content="　登　録　" %}</div>
    </form>
</div>
{% endblock %}

templates/careusers/careuser_list.html
{% extends "staffs/base.html" %}
{% load static %}
{% load django_bootstrap5 %}
{% load crispy_forms_tags %}
{% load crispy_forms_field %}
{% block extraheader %}
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'js/smooth-scroll.polyfills.min.js' %}"></script>
    <script src="{% static 'js/careuser_list.js' %}?4"></script>
{% endblock %}
{% block main %}
<div class="container-md">
    <h4 class="m-5">利用者一覧</h4>
    <div class="row my-3">
        <div class="col-3"></div>
        <div class="col-9 text-end">既に登録されているスケジュールの時間が変更されている場合　<br>重複する恐れがあります。入念にご確認の上追加してください。</div>
    </div>
    <div class="row my-3">
    {% if user.is_superuser %}
        <div class="col-3 text-start"><a href="{% url 'careusers:new' %}">{% bootstrap_button button_type="button" content="利用者新規登録" %}</a></div>
    {% else %}
        <div class="col-3"></div>
    {% endif %}
        <div class="col-9 d-flex justify-content-end align-items-center">
            <span class="me-2">チェックした項目を</span>
            <input type="radio" name="monthtype" class="form-check-input monthtype" id="add_this_month" value="this"{% if import_this_no_use %} disabled{% else %} checked{% endif %}><label class="form-check-label fs-5 me-2" for="add_this_month">{{ this_month.month }}月</label>
            <input type="radio" name="monthtype" class="form-check-input monthtype" id="add_next_month" value="next"{% if import_next_no_use %} disabled{% else %}{% if import_this_no_use is False %} checked{% endif %}{% endif %}><label class="form-check-label fs-5 me-2" for="add_next_month">{{ next_month.month }}月</label>
            <input type="number" name="start_day" style="width:60px;" class="form-control" id="start_day" value=1 maxlength="2"{% if import_btn_no_use %} disabled{% endif %}>
            <span class="">日から</span>
            <input type="number" name="end_day" style="width:60px;" class="form-control" id="end_day" value=31 maxlength="2"{% if import_btn_no_use %} disabled{% endif %}>
            <span class="me-2">日の間に</span>

            <a href="{% url 'schedules:import' %}"><button class="btn btn-danger" id="add_sche_btn" type="button"{% if import_btn_no_use %} disabled{% endif %}>予定追加</button></a>
        </div>
    </div>
    <div class="text-center my-4">
        <a class="mx-4 fs-4 tag scroll_tag_a">あ</a>
        <a class="mx-4 fs-4 tag scroll_tag_ka">か</a>
        <a class="mx-4 fs-4 tag scroll_tag_sa">さ</a>
        <a class="mx-4 fs-4 tag scroll_tag_ta">た</a>
        <a class="mx-4 fs-4 tag scroll_tag_na">な</a>
        <a class="mx-4 fs-4 tag scroll_tag_ha">は</a>
        <a class="mx-4 fs-4 tag scroll_tag_ma">ま</a>
        <a class="mx-4 fs-4 tag scroll_tag_ya">や</a>
        <a class="mx-4 fs-4 tag scroll_tag_ra">ら</a>
        <a class="mx-4 fs-4 tag scroll_tag_wa">わ</a>
    </div>
    {% if object_list %}
    <table class="table align-middle text-center">
        <thead>
            <tr>
                <th>利用者名</th>
                <th>履歴</th>
                <th>予定追加</th>
                <th colspan='5'>標準スケジュール</th>
                <th>変更</th>
            </tr>
        </thead>
        <tbody>
        {% for careuser in object_list %}
            <tr class="{% if forloop.counter|divisibleby:'2' %}bg_even{% else %}bg_uneven{% endif %}
            {% if careuser.last_kana|slice:':1' in tag_a %} tag_a
            {% elif careuser.last_kana|slice:':1' in tag_ka %} tag_ka
            {% elif careuser.last_kana|slice:':1' in tag_sa %} tag_sa
            {% elif careuser.last_kana|slice:':1' in tag_ta %} tag_ta
            {% elif careuser.last_kana|slice:':1' in tag_na %} tag_na
            {% elif careuser.last_kana|slice:':1' in tag_ha %} tag_ha
            {% elif careuser.last_kana|slice:':1' in tag_ma %} tag_ma
            {% elif careuser.last_kana|slice:':1' in tag_ya %} tag_ya
            {% elif careuser.last_kana|slice:':1' in tag_ra %} tag_ra
            {% elif careuser.last_kana|slice:':1' in tag_wa %} tag_wa
            {% endif %}">
                {% if careuser.is_active %}
                    {% if careuser.defaultschedule_set.all|length > 0 %}
                    <td rowspan="{{ careuser.defaultschedule_set.all|length }}">{% if user.is_superuser %}<a href="{% url 'careusers:edit' careuser.id %}">{{careuser.last_name}} {{careuser.first_name}}</a>{% else %}{{careuser.last_name}} {{careuser.first_name}}{% endif %}</td>
                    <td rowspan="{{ careuser.defaultschedule_set.all|length }}"><a href="{% url 'schedules:report_before' careuser=careuser.id page=1 %}"><button class="btn btn-warning" type="button">履歴</button></a></td>
                    <td rowspan="{{ careuser.defaultschedule_set.all|length }}"><a href="{% url 'careusers:def_sche_new' careuser.id %}">{% bootstrap_button button_type="button" content="予定追加" %}</a></td>
                    {% else %}
                    <td>{% if user.is_superuser %}<a href="{% url 'careusers:edit' careuser.id %}">{{careuser.last_name}} {{careuser.first_name}}</a>{% else %}{{careuser.last_name}} {{careuser.first_name}}{% endif %}</td>
                    <td><a href="{% url 'schedules:report_before' careuser=careuser.id page=1 %}"><button class="btn btn-warning" type="button">履歴</button></a></td>
                    <td><a href="{% url 'careusers:def_sche_new' careuser.id %}">{% bootstrap_button button_type="button" content="予定追加" %}</a></td>
                    {% endif %}
                    {% if careuser.defaultschedule_set.all|length > 0 %}
                        {% for sche in careuser.defaultschedule_set.all %}
                            {% if forloop.first == False %}
                            <tr class="{% if forloop.parentloop.counter|divisibleby:'2' %}bg_even{% else %}bg_uneven{% endif %}">
                            {% endif %}
                                <td class="text-start"><input type="checkbox" name="add_sche_check" class="checkboxinput form-check-input add_sche_check mx-2" value="{{sche.pk}}">{{ sche.get_schedule_name }}</td>
                                <td>{{ sche.get_start_time }}{{sche.get_end_time }}</td>
                                <td>{{ sche.service }}{% if sche.peoples > 1 %} × {{ sche.peoples }}名{% endif %}</td>
                                <td class="text-danger">{% if sche.add_stop %}自動追加停止中{% endif %}</td>
                                <td class="text-danger">{% if sche.no_set_staff %}ヘルパー自動登録なし{% endif %}</td>
                                <td><a href="{% url 'careusers:def_sche_edit' sche.pk %}">{% bootstrap_button button_type="button" content="変更・削除" %}</a></td>
                            {% if forloop.first == False %}
                            </tr> 
                            {% endif %}
                        {% endfor %}
                    {% else %}
                        <td colspan="7">登録なし</td>
                    {% endif %}
                {% else %}
                    <td>{% if user.is_superuser %}<a href="{% url 'careusers:edit' careuser.id %}">{{careuser.last_name}} {{careuser.first_name}}</a>{% else %}{{careuser.last_name}} {{careuser.first_name}}{% endif %}</td>
                    <td colspan="9">利用停止中</td>
                {% endif %}
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% else %}
    <div class="col mx-auto text-center my-5 lead">利用者は登録されておりません。</div>
    {% endif %}
</div>
{% endblock %}

templates/careusers/defaultschedule_delete.html
{% extends "staffs/base.html" %}
{% load django_bootstrap5 %}
{% load crispy_forms_tags %}
{% load crispy_forms_field %}
{% block main %}
<div class="container">
    <h4>スケジュール削除</h4>
    <div class="my-5"><a href="{% url 'careusers:list' %}">{% bootstrap_button button_type="button" content="戻る" %}</a></div>
    <form method="post">
        {% csrf_token %}
        {{form|crispy}}
        <p>以下のスケジュールを削除しますか？</p>
        <table class="table">
            <tbody>
                <tr><th>氏名</th><td>{{ defaultschedule.careuser }}様</td></tr>
                <tr><th>予定</th><td>{{ defaultschedule.get_schedule_name }}　{{ defaultschedule.get_start_time }}{{ defaultschedule.get_end_time }}</td></tr>
                <tr><th>サービス</th><td>{{ defaultschedule.service }}{% if defaultschedule.peoples > 1 %} × {{ defaultschedule.peoples }}名{% endif %}</td></tr>
                <tr><th>備考</th><td>{{ defaultschedule.biko }}</td></tr>
            </tbody>
        </table>
        {% bootstrap_button button_type="submit" button_class="btn btn-danger" content="削除" %}
    </form>
</div>
{% endblock %}

templates/careusers/defaultschedule_edit.html
{% extends "staffs/base.html" %}
{% load static %}
{% load django_bootstrap5 %}
{% load crispy_forms_tags %}
{% load crispy_forms_field %}
{% block extraheader %}
<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
<script src="{% static 'js/defaultschedule_form.js' %}?2"></script>
{% endblock %}
{% block main %}
<div class="container">
    <h4 class="my-5">{{defaultschedule.careuser}} 様　スケジュール編集</h4>
    <div class="row my-5">
        <div class="col-5">
            <a href="{% url 'careusers:list' %}">{% bootstrap_button button_type="button" content="　戻　る　" %}</a>
        </div>
        <div class="col-5 text-end">
            <a class="btn btn-danger btn-lg" href="{% url 'careusers:def_sche_delete' defaultschedule.pk %}">削除</a>
        </div>
    </div>
    <form method="post">
        {% csrf_token %}
        <div class="row my-3">
            <div class="col-2">{{ form.type | as_crispy_field }}</div>
        </div>
        <div id="weekbase_container">
            <div class="row">
                <div class="col-2">{{ form.weektype | as_crispy_field }}</div>
            </div>
            <div class="row mt-3">
                <div class="col-1 text-center">{{ form.sun.label }}</div>
                <div class="col-1 text-center">{{ form.mon.label }}</div>
                <div class="col-1 text-center">{{ form.tue.label }}</div>
                <div class="col-1 text-center">{{ form.wed.label }}</div>
                <div class="col-1 text-center">{{ form.thu.label }}</div>
                <div class="col-1 text-center">{{ form.fri.label }}</div>
                <div class="col-1 text-center">{{ form.sat.label }}</div>
            </div>
            <div class="row mb-5">
                <div class="col-1 text-center">{{ form.sun }}</div>
                <div class="col-1 text-center">{{ form.mon }}</div>
                <div class="col-1 text-center">{{ form.tue }}</div>
                <div class="col-1 text-center">{{ form.wed }}</div>
                <div class="col-1 text-center">{{ form.thu }}</div>
                <div class="col-1 text-center">{{ form.fri }}</div>
                <div class="col-1 text-center">{{ form.sat }}</div>
            </div>
        </div>
        <div id="daybase_container">
            <div class="row g-1">
                <div class="col-2">{{ form.daytype | as_crispy_field }}</div>
                <div class="col-1">{{ form.day | as_crispy_field }}</div>
            </div>
        </div>
        <div class="row mt-4 g-1">
            <div class="col-1">{{ form.start_h | as_crispy_field }}</div>
            <div class="col-1">{{ form.start_m | as_crispy_field }}</div>
        </div>
        <div class="row mt-4">
            <div class="col-3">{{ form.service | as_crispy_field }}</div>
            <div class="col-2">{{ form.peoples | as_crispy_field }}</div>
        </div>
        <div class="col-2 mt-4">{{ form.no_set_staff | as_crispy_field }}</div>
        <div class="col-2  mt-4">{{ form.add_stop | as_crispy_field }}</div>
        <div class="col-6 mt-4">{{ form.biko | as_crispy_field }}</div>
        <div class="col-6 mt-5 text-center">{% bootstrap_button button_type="submit" size="lg" content="　更　新　" %}</div>
    </form>
</div>
{% endblock %}