aggregates/urls.py
from django.urls import register_converter,path
from schedules import path_converter
from . import views
from django.contrib.auth.decorators import login_required

app_name = "aggregates"

register_converter(path_converter.FourDigitYearConverter,'yyyy')
register_converter(path_converter.TweDigitMonthConverter,'mm')
register_converter(path_converter.TweDigitDayConverter,'dd')

urlpatterns = [
    #以下はsuperuserのみアクセス可能(viewsにて制限)
    path("top/",login_required(views.TopView.as_view()),name="aggregate_top"),
    path("datalock/",login_required(views.DataLockView.as_view()),name="data_lock"),
    path("invoice_kaigo/<yyyy:year>/<mm:month>",login_required(views.KaigoView.as_view()),name="invoice_kaigo"),
    path('invoice_kaigo/export/<yyyy:year>/<mm:month>',login_required(views.kaigo_export), name='kaigo_export'),
    path("invoice_sougou/<yyyy:year>/<mm:month>",login_required(views.SougouView.as_view()),name="invoice_sougou"),
    path('invoice_sougou/export/<yyyy:year>/<mm:month>',login_required(views.sougou_export), name='sougou_export'),
    path("invoice/<str:kind>/<yyyy:year>/<mm:month>",login_required(views.InvoiceView.as_view()),name="invoice"),
    path('invoice/export/<str:kind>/<yyyy:year>/<mm:month>',login_required(views.export), name='invoice_export'),
    path("salary_employee/<yyyy:year>/<mm:month>",login_required(views.SalaryEmployeeView.as_view()),name="salary_employee"),
    path('salary_employee/export/<yyyy:year>/<mm:month>',login_required(views.salalyemployee_export), name='salaly_employee_export'),
    path("commission_employee/<yyyy:year>/<mm:month>",login_required(views.CommissionEmployeeView.as_view()),name="commission_employee"),
    path('commission_employee/export/<yyyy:year>/<mm:month>',login_required(views.commissionemployee_export), name='commission_employee_export'),
    path("worktime/<yyyy:year>/<mm:month>",login_required(views.WorktimeView.as_view()),name="worktime"),
    path('worktime/export/<yyyy:year>/<mm:month>',login_required(views.worktime_export), name='worktime_export'),
]

careusers/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = "careusers"

urlpatterns = [

    #以下はアクセス制限はviewsにて
    path("list/",login_required(views.CareuserListView.as_view()),name="list"),
    path("list/edit/<int:pk>/",login_required(views.CareuserEditView.as_view()),name="edit"),
    path("list/new/",login_required(views.CareuserCreateView.as_view()),name="new"),

    path("def_schedule/edit/<int:pk>/",login_required(views.DefscheduleEditView.as_view()),name="def_sche_edit"),
    path("def_schedule/new/<int:careuser_id>",login_required(views.DefscheduleCreateView.as_view()),name="def_sche_new"),
    path("def_schedule/delete/<int:pk>/",login_required(views.DefscheduleDeleteView.as_view()),name="def_sche_delete"),
]

hana/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from django.http import HttpResponse


urlpatterns = [
    #staffs.admin.pyのadmin.site.register(User, MyUserAdmin)もコメントアウト済み
    #path("ad_ksg/", admin.site.urls),
    path("staff/",include("staffs.urls")), 
    path("careuser/",include("careusers.urls")),
    path("service/",include("services.urls")),
    path("schedule/",include("schedules.urls")),
    path("aggregate/",include("aggregates.urls")),
    path("pdf/",include("pdfgen.urls")),
    url(r'^robots.txt$', lambda r: HttpResponse("User-agent: *\nDisallow: /", content_type="text/plain")),
]

schedules/urls.py
from django.urls import register_converter,path
from . import path_converter
from . import views,scheduleimportviews
from django.contrib.auth.decorators import login_required

app_name = "schedules"

register_converter(path_converter.FourDigitYearConverter,'yyyy')
register_converter(path_converter.TweDigitMonthConverter,'mm')
register_converter(path_converter.TweDigitDayConverter,'dd')

urlpatterns = [

    #ログイン済みの場合のみ
    path("day/",login_required(views.ScheduleDailyListView.as_view()),name="todaylist"),
    path("daily/<yyyy:year>/<mm:month>/<dd:day>",login_required(views.ScheduleDailyListView.as_view()), name='dailylist'),
    path("calender/",login_required(views.ScheduleCalendarListView.as_view()), name='calendar'),
    path("monthlycalender/<yyyy:year>/<mm:month>",login_required(views.ScheduleCalendarListView.as_view()), name="monthlycalendar"),
    path("report/<int:pk>/",login_required(views.ReportUpdateView.as_view()),name="report"),
    path("report/detail/<int:pk>/",login_required(views.ReportDetailView.as_view()),name="report_detail"),
    path("report_before/<int:careuser>/<int:page>/",login_required(views.ReportBeforeListView.as_view()),name="report_before"),
    path("add_request/",login_required(views.AddRequestView.as_view()),name="add_request"),

    #以下はstaffuserのみアクセス可能(viewsにて制限)
    path("month/",login_required(views.ScheduleListView.as_view()),name="thismonthlist"),
    path("monthly/<yyyy:year>/<mm:month>",login_required(views.ScheduleListView.as_view()),name="monthlylist"),
    path("monthly/<yyyy:year>/<mm:month>/<dd:day>",login_required(views.ScheduleListView.as_view()),name="dayselectlist"),
    path("import/",login_required(scheduleimportviews.ScheduleImportView.as_view()),name="import"),
    path("import_next/",login_required(scheduleimportviews.ScheduleImportView.as_view()),name="import_next"),
    path("edit/<int:pk>/",login_required(views.ScheduleEditView.as_view()),name="edit"),
    path("new/",login_required(views.ScheduleCreateView.as_view()),name="new"),
    path("delete/<int:pk>/",login_required(views.ScheduleDeleteView.as_view()),name="delete"),
    path("showstaff/<yyyy:year>/<mm:month>",login_required(views.ScheduleShowStaffView.as_view()),name="monthly_show_allstaff"),
    path("confirmed_addrequest/<int:pk>/",login_required(views.ConfirmedAddRequestView.as_view()),name="confirmed_add_request"),
    path("manage/",login_required(views.ManageTopView.as_view()),name="manage_top_thismonth"),
    path("manage/<yyyy:year>/<mm:month>",login_required(views.ManageTopView.as_view()),name="manage_top_monthly"),
    path("manage_monthly_check/<yyyy:year>/<mm:month>",login_required(views.ManageMonthlyCheckListView.as_view()),name="manage_monthly_check"),
]

staffs/urls.py
from django.contrib.auth import views
from django.urls import path
from .views import StaffListView,StaffEditView,StaffCreateView
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy


app_name = "staffs"

urlpatterns = [
    path("login/",views.LoginView.as_view(redirect_authenticated_user=True,template_name="staffs/login.html"),name="login"),
    path("logout/",views.LogoutView.as_view(),name="logout"),
    path("password_reset/", views.PasswordResetView.as_view(template_name="staffs/password_reset.html",email_template_name = 'staffs/password_reset_email.html',success_url = reverse_lazy('staffs:password_reset_done')), name="password_reset"),
    path("password_reset/done/", views.PasswordResetDoneView.as_view(template_name="staffs/password_reset_done.html"), name="password_reset_done"),
    path("password_reset/confirm/<uidb64>/<token>/", views.PasswordResetConfirmView.as_view(template_name="staffs/password_reset_confirm.html",success_url = reverse_lazy('staffs:password_reset_complete')), name="password_reset_confirm"),
    path("password_reset/complete/", views.PasswordResetCompleteView.as_view(template_name="staffs/password_reset_complete.html"), name="password_reset_complete"),


    #ログイン済みの場合のみ
    path("password_change/",login_required(views.PasswordChangeView.as_view(template_name="staffs/password_change.html",success_url = reverse_lazy('staffs:password_change_done'))),name="password_change"),
    path("password_change/done/",login_required(views.PasswordChangeDoneView.as_view(template_name="staffs/password_change_done.html")),name="password_change_done"),
    
    #以下はsuperuserのみアクセス可能(viewsにて制限)
    path("list/",login_required(StaffListView.as_view()),name="list"),
    path("list/edit/<int:pk>/",login_required(StaffEditView.as_view()),name="edit"),
    path("list/new/",login_required(StaffCreateView.as_view()),name="new"),
]

staffs/models.py
from django.db import models
from django.core.mail import send_mail
from django.contrib.auth.models import PermissionsMixin, UserManager
from django.contrib.auth.base_user import AbstractBaseUser
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone
from django.core.validators import MaxValueValidator
import datetime

class CustomUserManager(UserManager):
    """ユーザーマネージャー"""
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    """カスタムユーザーモデル　usernameを使わず、emailアドレスをユーザー名として使うようにしています。"""
    email = models.EmailField(_('メールアドレス'), unique=True)
    last_name = models.CharField(_('姓'), max_length=30)
    first_name = models.CharField(_('名'), max_length=30)
    password = models.CharField(max_length=128)

    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_(
            'Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    salary_choice = [(0,"---"),(1,"固定"),(2,"歩合")]
    last_kana  = models.CharField(verbose_name="せい",max_length=30)
    first_kana = models.CharField(verbose_name="めい",max_length=30)
    short_name = models.CharField(verbose_name="短縮名",max_length=30,default="",blank=True)
    birthday   = models.DateField(verbose_name="生年月日",blank=True, null=True)
    salary     = models.PositiveSmallIntegerField(verbose_name="給与体系",default=2,choices=salary_choice,validators=[MaxValueValidator(2)])
    pay_bike   = models.BooleanField(verbose_name="バイク代支給",default=False)
    staff_no   = models.PositiveSmallIntegerField(verbose_name="社員番号",blank=True, null=True,unique=True)
    postcode   = models.CharField(verbose_name="郵便番号",max_length=7)
    adr_ken    = models.CharField(verbose_name="都道府県",max_length=4)
    adr_siku   = models.CharField(verbose_name="市区町村",max_length=30)
    adr_tyou   = models.CharField(verbose_name="町名・番地",max_length=30)
    adr_bld    = models.CharField(verbose_name="ビル・マンション名",max_length=40,default="",blank=True)
    tel        = models.CharField(verbose_name="電話番号",max_length=15,default="",blank=True)
    phone      = models.CharField(verbose_name="携帯",max_length=15,default="",blank=True)
    shaho      = models.BooleanField(verbose_name="社会保険加入",default=False)
    join       = models.DateField(verbose_name="入社日",blank=True, null=True)
    biko       = models.TextField(verbose_name="備考",default="",blank=True)

    jimu       = models.BooleanField(verbose_name="事務員(利用停止済みを表示に必須)",default=False)
    servkan    = models.BooleanField(verbose_name="サービス提供責任者",default=False)
    kaigo      = models.BooleanField(verbose_name="介護職員(一覧表示に必須)",default=False)
    
    caremane   = models.BooleanField(verbose_name="ケアマネージャー",default=False)
    sousien    = models.BooleanField(verbose_name="相談支援専門員",default=False)
    servsou    = models.BooleanField(verbose_name="サービス相談員",default=False)
    kaifuku    = models.BooleanField(verbose_name="介護福祉士",default=False)
    jitumu     = models.BooleanField(verbose_name="実務者研修",default=False)
    shonin     = models.BooleanField(verbose_name="初任者研修",default=False)
    kisoken    = models.BooleanField(verbose_name="基礎研修(旧)",default=False)
    helper2    = models.BooleanField(verbose_name="ホームヘルパー2級(旧)",default=False)
    doukou     = models.BooleanField(verbose_name="同行援護従業者養成研修",default=False)
    reader     = models.BooleanField(verbose_name="グループリーダー",default=False)
    

    objects = CustomUserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def get_full_name(self):
        return f"{self.last_name}　{self.first_name}"

    def get_short_name(self):
        if self.short_name == None or self.short_name=="":
            s_name = self.last_name
        else:
            s_name = self.short_name
        return s_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

    def is_birthday(self):
        #誕生日判定
        birthday_flg = False
        now = datetime.datetime.now()
        now = timezone.make_aware(now)
        if self.birthday:
            if self.birthday.month == now.month and self.birthday.day == now.day:
                birthday_flg=True
        return birthday_flg

    @property
    def username(self):
        return self.email

    def __str__(self):
        return f"{self.last_name} {self.first_name}" 

staffs/forms.py
from django import forms
from staffs.models import User
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
import datetime

class StaffForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('last_name','first_name','last_kana','first_kana','short_name','birthday','salary','pay_bike','staff_no','postcode',
        'adr_ken','adr_siku','adr_tyou','adr_bld','email','is_staff','is_active','is_superuser','tel','phone','shaho','join','biko',
        'servkan','kaigo','jimu','caremane','sousien','servsou','kaifuku','jitumu','shonin',"kisoken",'helper2','doukou')
        year = int(datetime.datetime.now().strftime('%Y'))+1
        widgets = {
            'password': forms.PasswordInput(),
            'birthday': forms.SelectDateWidget(years=[x for x in range(1910,year)]),
            'join': forms.SelectDateWidget(years=[x for x in range(year-15,year)]),
        }

class StaffFormEdit(UserChangeForm):
    class Meta:
        model = User
        fields = ('last_name','first_name','last_kana','first_kana','short_name','birthday','salary','pay_bike','staff_no','postcode',
        'adr_ken','adr_siku','adr_tyou','adr_bld','email','is_staff','is_active','is_superuser','tel','phone','shaho','join','biko',
        'servkan','kaigo','jimu','caremane','sousien','servsou','kaifuku','jitumu','shonin',"kisoken",'helper2','doukou')
        year = int(datetime.datetime.now().strftime('%Y'))+1
        widgets = {
            'birthday': forms.SelectDateWidget(years=[x for x in range(1910,year)]),
            'join': forms.SelectDateWidget(years=[x for x in range(year-15,year)]),
        }

staffs/views.py
from .models import User
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView,TemplateView
from .forms import StaffForm,StaffFormEdit
from hana.mixins import SuperUserRequiredMixin


#以下superuserのみ表示（下のSuperUserRequiredMixinにて制限中）
class StaffListView(SuperUserRequiredMixin,ListView):
    model = User
    ordering = ['-is_active','pk']

class StaffCreateView(SuperUserRequiredMixin,CreateView):
    model = User
    form_class = StaffForm

    def get_success_url(self):
        return reverse_lazy('staffs:list')

class StaffEditView(SuperUserRequiredMixin,UpdateView):
    model = User
    form_class = StaffFormEdit
    
    def get_success_url(self):
        return reverse_lazy('staffs:list')

templates/staffs/base.html
{% load static %}
{% load django_bootstrap5 %}
{% load crispy_forms_tags %}
{% load crispy_forms_field %}
<html lang="ja">
<head>
    <meta charset="utf-8">
    <title>はなオンライン</title>
    <link rel="stylesheet" href="{% static 'css/common.css' %}?3">
    <meta name="robots" content="noindex, nofollow" /> 
    {% block pre_extraheader %}{% endblock %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% block extraheader %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-md flex-md-row navbar-dark bg-primary bg-gradient fixed-top">
    <div class="container-fluid justify-content-between">
        <a href="{% url 'schedules:todaylist' %}" class="navbar-brand mx-3">はなオンライン</a>
        <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#nav-bar" aria-controls="Navber" aria-expanded="true" aria-label="ナビゲーションの切替">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse ms-5" id="nav-bar">
            <ul class="navbar-nav">
                <li class="nav-item"><a class="nav-link" href="{% url 'schedules:todaylist' %}">予定一覧</a></li>
                {% if user.is_staff %}
                <li class="nav-item"><a class="nav-link" href="{% url 'schedules:calendar' %}?staff={{user.pk}}">月間カレンダー</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'schedules:thismonthlist' %}">予定作成</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'schedules:manage_top_thismonth' %}">実績管理</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'careusers:list' %}">利用者情報</a></li>                
                {% if user.is_superuser %}
                <li class="nav-item"><a class="nav-link" href="{% url 'aggregates:aggregate_top' %}">　集計　</a></li>
                {% endif %}
                {% else %}
                <li class="nav-item"><a class="nav-link" href="{% url 'schedules:calendar' %}">月間カレンダー</a></li>
                {% endif %}
                <li class="nav-item"><a class="nav-link" href="{% url 'staffs:password_change' %}">パスワード変更</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'staffs:logout' %}">ログアウト</a></li>
            </ul>
        </div>
    </div>
</nav>
<main>
    {% block main %}{% endblock %}
</main>
</body>
</html>

templates/staffs/base_no_login.html
{% load static %}
{% load django_bootstrap5 %}
{% load crispy_forms_tags %}
{% load crispy_forms_field %}
<html lang="ja">
<head>
    <meta charset="utf-8">
    <title>はなオンライン</title>
    <link rel="stylesheet" href="{% static 'css/common.css' %}">
    <meta name="robots" content="noindex, nofollow" /> 
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% block extraheader %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-expand flex-md-row navbar-dark bg-primary bg-gradient fixed-top">
    <div class="container justify-content-between">
        <a href="{% url 'schedules:todaylist' %}" class="navbar-brand">はなオンライン</a>
    </div>
</nav>
<main>
    {% block main %}{% endblock %}
</main>
</body>
</html>

templates/staffs/login.html
{% extends "staffs/base_no_login.html" %}
{% load django_bootstrap5 %}
{% load crispy_forms_tags %}
{% load crispy_forms_field %}
{% block extraheader %}
    <meta name="viewport" content="width=device-width, initial-scale=1" />
{% endblock %}
{% block main %}
    <div class="container mt-5">
        <div class="float-end my-4"><a href="{% url 'staffs:password_reset' %}">{% bootstrap_button button_type="button" content="パスワードを忘れた方" %}</a></div>
        <h4 class="my-3">ログイン</h4>
        <form method="post">
            {% csrf_token %}
            <input type="hidden" name="next" value="{{next}}" />
            {{ form.username | as_crispy_field }}
            {{ form.password | as_crispy_field }}
            <div class="text-center my-5">{% bootstrap_button button_type="submit" size="lg" content="　ログイン　" %}</div>
        </form>
    </div>
{% endblock %}

templates/staffs/password_change.html
{% extends "staffs/base.html" %}
{% load django_bootstrap5 %}
{% load crispy_forms_tags %}
{% load crispy_forms_field %}
{% block extraheader %}
    <meta name="viewport" content="width=device-width, initial-scale=1" />
{% endblock %}
{% block main %}
<div class="container">
    <h4 class="my-5">パスワード変更</h4>
    <div class=my-5><a href="{% url 'schedules:todaylist' %}">{% bootstrap_button button_type="button" content="戻る" %}</a></div>
    <form method="post">
        {% csrf_token %}
        {{form|crispy}}
        <div class="text-center my-5">{% bootstrap_button button_type="submit" size="lg" content="　変更　" %}</div>
    </form>
</div>
{% endblock %}

templates/staffs/password_change_done.html
{% extends "staffs/base.html" %}
{% load django_bootstrap5 %}
{% load crispy_forms_tags %}
{% load crispy_forms_field %}
{% block extraheader %}
    <meta name="viewport" content="width=device-width, initial-scale=1" />
{% endblock %}
{% block main %}
<div class="container"> 
    <h4 class="my-5">パスワード変更</h4>
    <p>パスワードの変更が完了しました。</p>
    <div class="text-center my-5"><a href="{% url 'schedules:todaylist' %}">{% bootstrap_button button_type="button" size="lg" content="戻る" %}</a></div>
</div>
{% endblock %}

templates/staffs/password_reset.html
{% extends "staffs/base_no_login.html" %}
{% load django_bootstrap5 %}
{% load crispy_forms_tags %}
{% load crispy_forms_field %}
{% block extraheader %}
    <meta name="viewport" content="width=device-width, initial-scale=1" />
{% endblock %}
{% block main %}
<div class="container">
    <h4 class="my-5">パスワードのリセット</h4>
    <div class=my-5><a href="{% url 'staffs:login'%}">{% bootstrap_button button_type="button" content="戻る" %}</a></div>
    <p>リセット操作を確認するため、登録されているメールアドレスに確認メールを送信します。</p>
    <p>登録されているメールアドレスを以下に入力してください。</p>
    <form method="post">
        {% csrf_token %}
        {{form|crispy}}
        <div class="text-center my-5">{% bootstrap_button button_type="submit" size="lg" content="　メールを送信　" %}</div>
    </form>
</div>
{% endblock %}

templates/staffs/password_reset_complete.html
{% extends "staffs/base_no_login.html" %}
{% load django_bootstrap5 %}
{% load crispy_forms_tags %}
{% load crispy_forms_field %}
{% block extraheader %}
    <meta name="viewport" content="width=device-width, initial-scale=1" />
{% endblock %}
{% block main %}
<div class="container">
    <h4 class="my-5">パスワードのリセット</h4>
    <p>パスワードのリセットが完了しました。</p>
    <div class="text-center my-5"><a href="{% url 'staffs:login' %}">{% bootstrap_button button_type="button" size="lg" content="戻る" %}</a></div>
</div>
 {% endblock %}

templates/staffs/password_reset_done.html
{% extends "staffs/base_no_login.html" %}
{% load django_bootstrap5 %}
{% load crispy_forms_tags %}
{% load crispy_forms_field %}
{% block extraheader %}
    <meta name="viewport" content="width=device-width, initial-scale=1" />
{% endblock %}
{% block main %}
<div class="container">
    <h4 class="my-5">パスワードのリセット</h4>
    <p>入力されたメールアドレスにリセット用のメールを送信しました。</p>
    <div class="text-center my-5"><a href="{% url 'staffs:login' %}">{% bootstrap_button button_type="button" size="lg" content="戻る" %}</a></div>
</div>
{% endblock %}

templates/staffs/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}このメールは {{ site_name }}よりパスワードリセットの操作が行われたため、送信されました。{% endblocktranslate %}

{% translate "次のページにアクセス頂き、新しいパスワードを設定してください。" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'staffs:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'ログイン用ID：' %} {{ user.get_username }}

{% translate "ご不明な点があれば会社までご連絡ください。" %}


{% blocktranslate %}株式会社はな　システム担当{% endblocktranslate %}

{% endautoescape %}

templates/staffs/user_list.html
{% extends "staffs/base.html" %}
{% load django_bootstrap5 %}
{% load crispy_forms_tags %}
{% load crispy_forms_field %}
{% block main %}
<div class="container">
    <h4 class="my-5">スタッフ一覧</h4>
    <div class="my-5"><a href="{{request.session.from}}">{% bootstrap_button button_type="button" content="　戻 る　" %}</a></div>
    <a href="{% url 'staffs:new'%}">{% bootstrap_button button_type="button" content="新規登録" %}</a>
    {% if object_list %}
    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>スタッフ名</th>
                <th>無効</th>
                <th>システム権限</th>
                <th>管理者</th>
                <th>バイク代支給</th>
                <th>資格</th>
            </tr>
        </thead>
        <tbody>
        {% for staff in object_list %}
            <tr>
                <td>{{staff.id}}</td>
                <td><a href="{% url 'staffs:edit' staff.pk%}">{% if not staff.last_name and not staff.first_name %}未入力{% else %}{{staff.last_name}} {{staff.first_name}}{% endif %}</a></td>
                <td>{% if not staff.is_active %}無効{% endif %}</td>
                <td>{% if staff.is_superuser %}システム管理者{% endif %}</td>
                <td>{% if staff.is_staff %}管理者{% endif %}</td>
                <td>{% if staff.pay_bike %}バイク代支給{% endif %}</td>
                <td>{% if staff.servkan%} サービス提供責任者 {% endif %}
                    {% if staff.caremane %} ケアマネージャー {% endif %}
                    {% if staff.sousien %} 相談支援専門員 {% endif %}
                    {% if staff.servsou %} サービス相談員 {% endif %}
                    {% if staff.kaifuku %} 介護福祉士 {% endif %}
                    {% if staff.jitumu %} 実務者研修 {% endif %}
                    {% if staff.shonin %} 初任者研修 {% endif %}
                    {% if staff.kisoken %} 基礎研修 {% endif %}
                    {% if staff.helper2 %} ホームヘルパー2級 {% endif %}
                    {% if staff.doukou %} 同行援護従業者養成研修 {% endif %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% else %}
    <div class="col mx-auto text-center my-5 lead">スタッフは登録されておりません。</div>
    {% endif %}
</div>
{% endblock %}