hana/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from django.http import HttpResponse


urlpatterns = [
    #staffs.admin.pyのadmin.site.register(User, MyUserAdmin)もコメントアウト済み
    #path("ad_ksg/", admin.site.urls),
    path("staff/",include("staffs.urls")), 
    path("careuser/",include("careusers.urls")),
    path("service/",include("services.urls")),
    path("schedule/",include("schedules.urls")),
    path("aggregate/",include("aggregates.urls")),
    path("pdf/",include("pdfgen.urls")),
    url(r'^robots.txt$', lambda r: HttpResponse("User-agent: *\nDisallow: /", content_type="text/plain")),
]

pdfgen/urls.py
from django.urls import register_converter,path
from schedules import path_converter
from . import views
from django.contrib.auth.decorators import login_required

app_name = "pdfgen"

register_converter(path_converter.FourDigitYearConverter,'yyyy')
register_converter(path_converter.TweDigitMonthConverter,'mm')
register_converter(path_converter.TweDigitDayConverter,'dd')

urlpatterns = [

    #ログイン済みの場合のみ
    path("calender/<yyyy:year>/<mm:month>",login_required(views.PrintCalendarView.as_view()),name="calendar"),

    #以下はstaffuserのみアクセス可能(viewsにて制限)
    path("monthly_report/<yyyy:year>/<mm:month>",login_required(views.PrintMonthlyReportView.as_view()),name="monthlyreport"),
    path("visitedform/<yyyy:year>/<mm:month>",login_required(views.PrintVisitedListFormView.as_view()),name="visitedlistform"),
    path("visitedgeneralform",login_required(views.PrintVisitedGeneralFormView.as_view()),name="visitedgeneralform"),
    path("collectchecksheet/<yyyy:year>/<mm:month>",login_required(views.PrintArchiveCollectCheckListView.as_view()),name="collectchecksheet"),
]

schedules/urls.py
from django.urls import register_converter,path
from . import path_converter
from . import views,scheduleimportviews
from django.contrib.auth.decorators import login_required

app_name = "schedules"

register_converter(path_converter.FourDigitYearConverter,'yyyy')
register_converter(path_converter.TweDigitMonthConverter,'mm')
register_converter(path_converter.TweDigitDayConverter,'dd')

urlpatterns = [

    #ログイン済みの場合のみ
    path("day/",login_required(views.ScheduleDailyListView.as_view()),name="todaylist"),
    path("daily/<yyyy:year>/<mm:month>/<dd:day>",login_required(views.ScheduleDailyListView.as_view()), name='dailylist'),
    path("calender/",login_required(views.ScheduleCalendarListView.as_view()), name='calendar'),
    path("monthlycalender/<yyyy:year>/<mm:month>",login_required(views.ScheduleCalendarListView.as_view()), name="monthlycalendar"),
    path("report/<int:pk>/",login_required(views.ReportUpdateView.as_view()),name="report"),
    path("report/detail/<int:pk>/",login_required(views.ReportDetailView.as_view()),name="report_detail"),
    path("report_before/<int:careuser>/<int:page>/",login_required(views.ReportBeforeListView.as_view()),name="report_before"),
    path("add_request/",login_required(views.AddRequestView.as_view()),name="add_request"),

    #以下はstaffuserのみアクセス可能(viewsにて制限)
    path("month/",login_required(views.ScheduleListView.as_view()),name="thismonthlist"),
    path("monthly/<yyyy:year>/<mm:month>",login_required(views.ScheduleListView.as_view()),name="monthlylist"),
    path("monthly/<yyyy:year>/<mm:month>/<dd:day>",login_required(views.ScheduleListView.as_view()),name="dayselectlist"),
    path("import/",login_required(scheduleimportviews.ScheduleImportView.as_view()),name="import"),
    path("import_next/",login_required(scheduleimportviews.ScheduleImportView.as_view()),name="import_next"),
    path("edit/<int:pk>/",login_required(views.ScheduleEditView.as_view()),name="edit"),
    path("new/",login_required(views.ScheduleCreateView.as_view()),name="new"),
    path("delete/<int:pk>/",login_required(views.ScheduleDeleteView.as_view()),name="delete"),
    path("showstaff/<yyyy:year>/<mm:month>",login_required(views.ScheduleShowStaffView.as_view()),name="monthly_show_allstaff"),
    path("confirmed_addrequest/<int:pk>/",login_required(views.ConfirmedAddRequestView.as_view()),name="confirmed_add_request"),
    path("manage/",login_required(views.ManageTopView.as_view()),name="manage_top_thismonth"),
    path("manage/<yyyy:year>/<mm:month>",login_required(views.ManageTopView.as_view()),name="manage_top_monthly"),
    path("manage_monthly_check/<yyyy:year>/<mm:month>",login_required(views.ManageMonthlyCheckListView.as_view()),name="manage_monthly_check"),
]

schedules/models.py
from django.conf import settings
from django.db import models
from services.models import Service
from staffs.models import User
from careusers.models import CareUser,DefaultSchedule
import datetime
from django.utils.timezone import make_aware
from django.core.validators import MaxValueValidator
from django.core.exceptions import ValidationError

#バリデーション
def check_time(datetime_value):
        #現在時刻
        now  = make_aware(datetime.datetime.now())
        if datetime_value > now:
            raise ValidationError('まだ、サービス開始時刻より前です')

class Schedule(models.Model):

    peoples_choice = [(1,"1名"),(2,"2名"),(3,"3名"),(4,"4名")]

    careuser       = models.ForeignKey(CareUser,verbose_name="利用者名",on_delete=models.RESTRICT)
    start_date     = models.DateTimeField(verbose_name="予定日時")
    end_date       = models.DateTimeField(verbose_name="予定終了日時",blank=True,null=True)
    service        = models.ForeignKey(Service,verbose_name="利用サービス",on_delete=models.RESTRICT,null=True)
    peoples        = models.PositiveSmallIntegerField(verbose_name="必要人数",default=1,choices=peoples_choice,validators=[MaxValueValidator(4)])
    staff1         = models.ForeignKey(User,verbose_name="担当スタッフ１",blank=True,null=True,related_name = "staffs1",on_delete=models.RESTRICT)
    staff2         = models.ForeignKey(User,verbose_name="担当スタッフ２",blank=True,null=True,related_name = "staffs2",on_delete=models.RESTRICT)
    staff3         = models.ForeignKey(User,verbose_name="担当スタッフ３",blank=True,null=True,related_name = "staffs3",on_delete=models.RESTRICT)
    staff4         = models.ForeignKey(User,verbose_name="担当スタッフ４",blank=True,null=True,related_name = "staffs4",on_delete=models.RESTRICT)
    tr_staff1      = models.ForeignKey(User,verbose_name="研修スタッフ１",blank=True,null=True,related_name = "tr_staffs1",on_delete=models.RESTRICT)
    tr_staff2      = models.ForeignKey(User,verbose_name="研修スタッフ２",blank=True,null=True,related_name = "tr_staffs2",on_delete=models.RESTRICT)
    tr_staff3      = models.ForeignKey(User,verbose_name="研修スタッフ３",blank=True,null=True,related_name = "tr_staffs3",on_delete=models.RESTRICT)
    tr_staff4      = models.ForeignKey(User,verbose_name="研修スタッフ４",blank=True,null=True,related_name = "tr_staffs4",on_delete=models.RESTRICT)
    biko           = models.TextField(verbose_name="備考",max_length=200,default="",blank=True)
    def_sche       = models.ForeignKey(DefaultSchedule,verbose_name="標準スケジュールからの登録",blank=True,null=True,related_name = "def_sche",on_delete=models.SET_NULL)
    careuser_check_level = models.PositiveSmallIntegerField(verbose_name="利用者チェックフラグ",default=0,blank=True)
    staff_check_level    = models.PositiveSmallIntegerField(verbose_name="スタッフチェックフラグ",default=0,blank=True)
    cancel_flg     = models.BooleanField(verbose_name="予定キャンセル",default=False)
    created_by     = models.ForeignKey(settings.AUTH_USER_MODEL,verbose_name="登録スタッフ",on_delete=models.RESTRICT)
    created_at     = models.DateTimeField(verbose_name="登録日",auto_now_add=True)
    updated_at     = models.DateTimeField(verbose_name="更新日",blank=True,null=True)


    def __str__(self):
        return f"{self.careuser}" 

    def staffs(self):
        name_staffs  = ""
        #スタッフ表示
        if self.staff1 != None:
            name_staffs += self.staff1.get_short_name()
        if self.staff2 != None:
            if name_staffs  != "":
               name_staffs += "・" 
            name_staffs += self.staff2.get_short_name()
        if self.staff3 != None:
            if name_staffs  != "":
                   name_staffs += "・" 
            name_staffs += self.staff3.get_short_name()
        if self.staff4 != None:
            if name_staffs  != "":
                   name_staffs += "・" 
            name_staffs += self.staff4.get_short_name()

        return name_staffs

    def staffs_and_trainer(self):
        name_staffs  = ""
        if self.cancel_flg:
            name_staffs  = "キャンセル"
        else:
            #スタッフと研修員表示
            if self.staff1 != None:
                name_staffs += self.staff1.get_short_name()
            if self.staff2 != None:
                if name_staffs  != "":
                    name_staffs += "・" 
                name_staffs += self.staff2.get_short_name()
            if self.staff3 != None:
                if name_staffs  != "":
                    name_staffs += "・" 
                name_staffs += self.staff3.get_short_name()
            if self.staff4 != None:
                if name_staffs  != "":
                    name_staffs += "・" 
                name_staffs += self.staff4.get_short_name()
            if self.tr_staff1 != None:
                if name_staffs  != "":
                    name_staffs += "・" 
                name_staffs += self.tr_staff1.get_short_name()
            if self.tr_staff2 != None:
                if name_staffs  != "":
                    name_staffs += "・" 
                name_staffs += self.tr_staff2.get_short_name()
            if self.tr_staff3 != None:
                if name_staffs  != "":
                    name_staffs += "・" 
                name_staffs += self.tr_staff3.get_short_name()
            if self.tr_staff4 != None:
                if name_staffs  != "":
                    name_staffs += "・" 
                name_staffs += self.tr_staff4.get_short_name()

        return name_staffs

class Report(models.Model):
    error_choice = [(0,"なし"),(11,"開始・終了時間不整合"),(12,"実績合計時間が内訳合計時間と不一致"),(13,"サービス実施時間が最低時間以下"),(14,"サービス実施時間が15分以上超過"),(15,"年月日が不一致"),(16,"担当スタッフの移動時間が5分未満"),(17,"サービス必要人員数不足"),(90,"開始時間・終了時間が未入力")]
    schedule    = models.OneToOneField(Schedule,on_delete=models.CASCADE)
    #利用者様確認（利用者によってメール送信した場合もあり）
    careuser_confirmed = models.BooleanField(verbose_name="利用者様確認済み（確認後は登録ヘルパーさんは修正不可となります。）",default=False)
    email_sent_date    = models.DateTimeField(verbose_name="実績記録e-mail送信日時",null=True)
    service_in_date    = models.DateTimeField(verbose_name="サービス開始日時",null=True)
    service_out_date   = models.DateTimeField(verbose_name="サービス終了日時",null=True)
    mix_reverse        = models.BooleanField(verbose_name="混合サービス順序",default=False)
    in_time_main       = models.PositiveSmallIntegerField(verbose_name="内訳時間メイン(分)",default=0,blank=True,validators=[MaxValueValidator(4320)])
    in_time_sub        = models.PositiveSmallIntegerField(verbose_name="内訳時間サブ(分)",default=0,blank=True,validators=[MaxValueValidator(4320)])
    first              = models.BooleanField(verbose_name="初回",default=False)
    emergency          = models.BooleanField(verbose_name="緊急",default=False)
    error_code         = models.PositiveSmallIntegerField(verbose_name="エラーコード",default=0,choices=error_choice,validators=[MaxValueValidator(100)])
    warnings           = models.CharField(verbose_name="確認事項",max_length=150,default='',blank=True,null=True)
    error_warn_allowed = models.BooleanField(verbose_name="error・warningチェック済み",default=False)
    #事前チェック
    facecolor_choice = [(0,"---"),(1,"良"),(2,"不良")]
    hakkan_choice = [(0,"---"),(1,"有"),(2,"無")]
    face_color   = models.PositiveSmallIntegerField(verbose_name="顔色",default=0,choices=facecolor_choice,validators=[MaxValueValidator(2)])
    hakkan       = models.PositiveSmallIntegerField(verbose_name="発汗",default=0,choices=hakkan_choice,validators=[MaxValueValidator(2)])
    body_temp    = models.FloatField(verbose_name="体温",blank=True,null=True,validators=[MaxValueValidator(45)])
    blood_pre_h  = models.PositiveSmallIntegerField(verbose_name="血圧High",null=True,blank=True,validators=[MaxValueValidator(300)])
    blood_pre_l  = models.PositiveSmallIntegerField(verbose_name="血圧Low",null=True,blank=True,validators=[MaxValueValidator(300)])
    #退室時
    after_fire   = models.BooleanField(verbose_name="火元",default=False)
    after_elec   = models.BooleanField(verbose_name="電気",default=False)
    after_water  = models.BooleanField(verbose_name="水道",default=False)
    after_close  = models.BooleanField(verbose_name="戸締り",default=False)

    #身体介護/////////////////////////////////////////////////////////////////////////////////////////////////////////
    #排泄介助
    urination_a_choice = [(0,"---"),(1,"少"),(2,"並"),(3,"多")]
    toilet       = models.BooleanField(verbose_name="トイレ介助",default=False)
    p_toilet     = models.BooleanField(verbose_name="Pトイレ介助",default=False)
    diapers      = models.BooleanField(verbose_name="おむつ・パッド交換",default=False)
    pads         = models.BooleanField(verbose_name="パッド確認",default=False)
    nyouki       = models.BooleanField(verbose_name="尿器介助・洗浄",default=False)
    linen        = models.BooleanField(verbose_name="リネン等処理",default=False)
    inbu         = models.BooleanField(verbose_name="陰部清潔",default=False)
    
    urination_t  = models.PositiveSmallIntegerField(verbose_name="排尿回数",default=None,null=True,blank=True,validators=[MaxValueValidator(99)])
    urination_a  = models.PositiveSmallIntegerField(verbose_name="排尿量",default=0,choices=urination_a_choice,validators=[MaxValueValidator(3)])
    defecation_t = models.PositiveSmallIntegerField(verbose_name="排便回数",default=None,null=True,blank=True,validators=[MaxValueValidator(99)])
    defecation_s = models.CharField(verbose_name="排便状態",max_length=50,default="",blank=True)
    #食事介助
    eating_choice = [(0,"---"),(1,"全"),(2,"一部")]
    posture      = models.BooleanField(verbose_name="姿勢の確保",default=False)
    eating       = models.PositiveSmallIntegerField(verbose_name="摂食介助",default=0,choices=eating_choice,validators=[MaxValueValidator(2)])
    eat_a        = models.PositiveSmallIntegerField(verbose_name="食事量",default=None,null=True,blank=True,validators=[MaxValueValidator(100)])
    drink_a      = models.PositiveSmallIntegerField(verbose_name="水分補給",default=None,null=True,blank=True,validators=[MaxValueValidator(9999)])
    #清拭入浴
    bedbath_choice = [(0,"---"),(1,"全身"),(2,"部分")]
    bath_choice  = [(0,"---"),(1,"全身浴"),(2,"全身シャワー浴"),(3,"部分浴：手"),(4,"部分浴：足"),(5,"部分浴：手足")]

templates/schedules/schedule_list.html
{% extends "staffs/base.html" %}
{% load static %}
{% load django_bootstrap5 %}
{% load crispy_forms_tags %}
{% load crispy_forms_field %}
{% block pre_extraheader %}
    <script src="{% static 'js/popper.min.js' %}"></script>
{% endblock %}
{% block extraheader %}
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'js/smooth-scroll.polyfills.min.js' %}"></script>
    <script src="{% static 'js/schedule_list.js' %}?15"></script>
    <link rel="stylesheet" href="{% static 'css/schedule_list.css' %}?9">
{% endblock %}
{% block main %}
<div class="container-md">
    <div class="fixed-top page_ctrl py-2">
        <div class="row text-center align-middle my-3">
            <div class="col-4"><a href="{% url 'schedules:monthlylist' year=before_month.year month=before_month.month %}">{% bootstrap_button button_type="button" button_class="btn-primary month_btn" content="　前月　" %}</a></div>
            <div class="col-4 fs-2">{{this_month.year}}年{{this_month.month}}月</div>
            <div class="col-4"><a href="{% url 'schedules:monthlylist' year=next_month.year month=next_month.month %}">{% bootstrap_button button_type="button" button_class="btn-primary month_btn" content="　翌月　" %}</a></div>
        </div>
        <form method="get" action="" name="filter_form" id="search_form">
        <div class="row d-flex align-items-center">
            <div class="col-3 px-5 text-end"><a href="{% url 'schedules:new'%}{% if selected_careuser %}?careuser={{selected_careuser.pk}}{% endif %}">{% bootstrap_button button_type="button" content="新規登録" %}</a></div>
            <div class="col-3">
                <label for="careuser">利用者名検索</label>
                <select name="careuser" class="select form-select" id="careuser">
                    <option value=""{% if selected_careuser is None %} selected{% endif %}>---------</option>
                    {% for careuser in careuser_obj %}
                    <option value="{{careuser.pk}}"{% if careuser.pk == selected_careuser.pk %} selected{% endif %}>{{ careuser }}{% if not careuser.is_active %} [停止済]{% endif %}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="col-3">
                <label for="staff">スタッフ名検索</label>
                <select name="staff" class="select form-select" id="staff">
                    <option value=""{% if selected_staff is None %} selected{% endif %}>---------</option>
                    {% for staff in staff_obj %}
                    <option value="{{staff.pk}}"{% if staff.pk == selected_staff.pk %} selected{% endif %}>{{ staff }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <div class="row d-flex align-items-end pt-2">
            <div class="col-3"></div>
            <div class="col-3 text-end"><a href="{% url 'schedules:monthlylist' year=this_month.year month=this_month.month %}?errors=false">{% bootstrap_button button_type="button" button_class="btn-primary" content="月間全件表示" %}</a></div>
            <div class="col-3">
                <label for="staff">サービス種別検索</label>
                <select name="service_kind" class="select form-select" id="service_kind">
                    <option value=""{% if selected_service_kind is None %} selected{% endif %}>---------</option>
                    {% for kind,name in service_kind_obj.items %}
                    <option value="{{ kind }}"{% if kind == selected_service_kind %} selected{% endif %}>{{ name }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="col-3"><a href="{% url 'schedules:monthlycalendar' year=this_month.year month=this_month.month %}{% if selected_careuser or selected_staff %}?{% if selected_careuser %}careuser={{selected_careuser.pk}}{% elif selected_staff %}staff={{selected_staff.pk}}{% endif %}{% endif %}">{% bootstrap_button button_type="button" button_class="btn-primary" content="カレンダー表示" %}</a>
            </div>
        </div>
        </form>
    </div>
    <div class="content">
    {% if selected_errors %}
        <h4 class="mb-5 text-danger">要注意リスト</h4>
    {% endif %}
    {% if object_list %}
        <table class="table align-middle text-center">
            <thead>
                <tr>
                    <th>日</th>
                    <th>時</th>
                    <th>実績</th>
                    <th>利用者</th>
                    <th>スタッフ</th>
                    <th>変更</th>
                    <th>サービス内容</th>
                    <th>実施記録</th>
                </tr>
            </thead>
            <tbody>
        {% regroup object_list by start_date|date:"j日(D)" as object_list_by_day %}
        {% for day in object_list_by_day %}
            <tr class="{% if forloop.counter|divisibleby:'2' %}bg_even{% else %}bg_uneven{% endif %}">
                <td{% if day.list|length > 1 %} rowspan="{{ day.list|length }}"{% endif %}{% if anchor_day and day.grouper == anchor_day %} id="anchor"{% endif %}>{{ day.grouper }}</td>
            {% for schedule in day.list %}
            {% if forloop.first == False %}
            <tr class="{% if forloop.parentloop.counter|divisibleby:'2' %}bg_even{% else %}bg_uneven{% endif %}">
            {% endif %}
                <td>{{ schedule.start_date|date:"G:i" }}～{{ schedule.end_date|date:"G:i" }}</td>
                <td>
                    {% if schedule.report.careuser_confirmed %}
                        {% if schedule.report.error_code > 0 %}
                        <span class="text-danger">
                            {% if schedule.start_date == schedule.report.service_in_date and schedule.end_date == schedule.report.service_out_date%}
                                予定通り
                            {% else %}
                                {% if schedule.start_date|date:"Ymd" != schedule.report.service_in_date|date:"Ymd" %}{{ schedule.report.service_in_date|date:"Y/m/d" }}<br>{% endif %}
                                {{schedule.report.service_in_date|date:"G:i"}}～{{schedule.report.service_out_date|date:"G:i"}}
                            {% endif %}
                            <br>{{ schedule.report.get_error_code_display }}
                        </span>
                        {% elif not schedule.report.error_warn_allowed and schedule.report.warnings != "" %}
                        <span class="text-primary">
                            {% if schedule.start_date == schedule.report.service_in_date and schedule.end_date == schedule.report.service_out_date%}
                                予定通り
                            {% else %}
                                {% if schedule.start_date|date:"Ymd" != schedule.report.service_in_date|date:"Ymd" %}{{ schedule.report.service_in_date|date:"Y/m/d" }}<br>{% endif %}
                                {{schedule.report.service_in_date|date:"G:i"}}～{{schedule.report.service_out_date|date:"G:i"}}
                            {% endif %}
                            <br>{{ schedule.report.warnings }}
                        </span>
                        {% elif schedule.start_date != schedule.report.service_in_date or schedule.end_date != schedule.report.service_out_date%}
                        <span>
                            {% if schedule.start_date|date:"Ymd" != schedule.report.service_in_date|date:"Ymd" %}{{ schedule.report.service_in_date|date:"Y/m/d" }}<br>{% endif %}
                            {{schedule.report.service_in_date|date:"G:i"}}～{{schedule.report.service_out_date|date:"G:i"}}
                        </span>
                        {% else %}
                        <span>予定通り</span>
                        {% endif %}
                    {% elif schedule.cancel_flg %}
                        <span>キャンセル</span>
                    {% elif schedule.start_date < time_now %}
                        <span class="text-danger">未入力</span>
                    {% endif %}
                </td>
                <td{% if schedule.careuser_check_level == 2 %} class="table-warning" data-bs-toggle="tooltip" data-bs-placement="bottom" title="未選択"{% elif schedule.careuser_check_level == 3 %} class="table-danger" data-bs-toggle="tooltip" data-bs-placement="bottom" title="時間重複"{% endif %}>{% if schedule.def_sche_id == None %}[追加] {% endif %}{{ schedule.careuser }}</td>
                <td{% if schedule.staff_check_level == 2 %} class="table-warning" data-bs-toggle="tooltip" data-bs-placement="bottom" title="未選択"{% elif schedule.staff_check_level == 3 %} class="table-danger" data-bs-toggle="tooltip" data-bs-placement="bottom" title="時間重複"{% endif %}>{% if schedule.peoples > 1 %}[{{ schedule.peoples }}名]{% endif %}{{ schedule.staffs_and_trainer }}</td>
                {% if schedule.careuser.is_active is True %}
                {% if not data_lock_date >= schedule.start_date and not data_lock_date >= schedule.report.service_in_date or user.is_superuser %}
                <td><a href="{% url 'schedules:edit' schedule.pk %}"><button class="btn btn-primary schedule_edit_btn" type="button">変更</button></a></td>
                {% else %}
                <td><button class="btn btn-primary schedule_edit_btn" type="button" disabled>確定済</button></td>
                {% endif %}
                {% else %}
                <td>利用停止</td>
                {% endif %}
                <td>{% if schedule.service.kind == 0 %}[介護] {% elif schedule.service.kind == 1 %}[障害] {% endif %}{{ schedule.service.title }}</td>
                {% if schedule.cancel_flg %}
                <td><button class="btn btn-outline-dark report_btn" disabled>キャンセル</button></td>
                {% elif schedule.start_date > time_now %}
                <td><button class="btn btn-outline-primary report_btn" disabled>未実施</button></td>
                {% elif schedule.report.careuser_confirmed is False %}
                {% if not data_lock_date >= schedule.start_date and not data_lock_date >= schedule.report.service_in_date or user.is_superuser %}
                <td><a href="{% url 'schedules:report' schedule.report.pk %}"><button class="btn btn-danger report_btn" type="button">未入力</button></a></td>
                {% else %}
                <td><button class="btn btn-danger report_btn" type="button" disabled>未入力</button></td>
                {% endif %}
                {% else %}
                <td><a href="{% url 'schedules:report_detail' schedule.report.pk %}"><button class="btn btn-outline-primary report_btn" type="button">記録確認</button></a></td>
                {% endif %}
            {% endfor %}
            </tr>
        {% endfor %}
            </tbody>
        </table>
    {% else %}
        {% if selected_errors %}
        <div class="col mx-auto text-center my-5 lead">要注意のシフトはありませんでした。</div>
        {% else %}
        <div class="col mx-auto text-center my-5 lead">スケジュールは登録されておりません。</div>
        {% endif %}
        
    {% endif %}
    </div>
</div>
{% endblock %}

templates/schedules/top.html
{% extends "staffs/base.html" %}
{% load static %}
{% load django_bootstrap5 %}
{% load crispy_forms_tags %}
{% load crispy_forms_field %}
{% block pre_extraheader %}
    <script src="{% static 'js/popper.min.js' %}"></script>
{% endblock %}
{% block extraheader %}
    <link rel="stylesheet" href="{% static 'css/common.css' %}">
    <script src="{% static 'js/jquery-3.6.0.slim.min.js' %}"></script>
    <script src="{% static 'js/schedule_list.js' %}"></script>
{% endblock %}
{% block main %}
<h2 class="my-5">{{ user.get_full_name }}様　お疲れ様です。</h2>
<h3>本日・明日の予定一覧</h3>
{% if object_list %}
<table class="table align-middle text-center">
    <thead>
        <tr>
            <th>日</th>
            <th>時</th>
            <th>利用者</th>
            <th>サービス内容</th>
            <th>報告書作成</th>
        </tr>
    </thead>
    <tbody>
{% regroup object_list by start_date|date:"j日" as object_list_by_day %}
{% for day in object_list_by_day %}
    <tr class="{% if forloop.counter|divisibleby:'2' %}bg_even{% else %}bg_uneven{% endif %}">
        <td{% if day.list|length > 1 %} rowspan="{{ day.list|length }}"{% endif %}>{{ day.grouper }}</td>
    {% for schedule in day.list %}
    {% if forloop.first == False %}
    <tr class="{% if forloop.parentloop.counter|divisibleby:'2' %}bg_even{% else %}bg_uneven{% endif %}">
    {% endif %}
        <td{% if schedule.check_flg %} class="table-danger"{% endif %}>{{ schedule.start_date|date:"G:i" }}～{{ schedule.end_date|date:"G:i" }}{% if schedule.def_sche_id == 0 %}【臨時】{% endif %}
            {% if schedule.staff1 != user and schedule.staff2 != user and schedule.staff3 != user and schedule.staff4 != user %}【同行】{% endif %}  
        </td>
        <td{% if schedule.careuser_check_level == 2 %} class="table-warning" data-bs-toggle="tooltip" data-bs-placement="bottom" title="未選択"
        {% elif schedule.careuser_check_level == 3 %} class="table-danger" data-bs-toggle="tooltip" data-bs-placement="bottom" title="時間重複"{% endif %}>{{ schedule.careuser }} 様</td>
        <td{% if schedule.check_flg %} class="table-danger"{% endif %}>{{ schedule.service }}</td>
        <td{% if schedule.check_flg %} class="table-danger"{% endif %}><a href="{% url 'schedules:edit' schedule.pk %}">{% bootstrap_button button_type="button" content="報告書" %}</a></td>
        {% endfor %}
    </tr>
{% endfor %}
    </tbody>
</table>
{% else %}
<p>スケジュールは登録されておりません。</p>
{% endif %}
{% endblock %}