aggregates/urls.py
from django.urls import register_converter,path
from schedules import path_converter
from . import views
from django.contrib.auth.decorators import login_required

app_name = "aggregates"

register_converter(path_converter.FourDigitYearConverter,'yyyy')
register_converter(path_converter.TweDigitMonthConverter,'mm')
register_converter(path_converter.TweDigitDayConverter,'dd')

urlpatterns = [
    #以下はsuperuserのみアクセス可能(viewsにて制限)
    path("top/",login_required(views.TopView.as_view()),name="aggregate_top"),
    path("datalock/",login_required(views.DataLockView.as_view()),name="data_lock"),
    path("invoice_kaigo/<yyyy:year>/<mm:month>",login_required(views.KaigoView.as_view()),name="invoice_kaigo"),
    path('invoice_kaigo/export/<yyyy:year>/<mm:month>',login_required(views.kaigo_export), name='kaigo_export'),
    path("invoice_sougou/<yyyy:year>/<mm:month>",login_required(views.SougouView.as_view()),name="invoice_sougou"),
    path('invoice_sougou/export/<yyyy:year>/<mm:month>',login_required(views.sougou_export), name='sougou_export'),
    path("invoice/<str:kind>/<yyyy:year>/<mm:month>",login_required(views.InvoiceView.as_view()),name="invoice"),
    path('invoice/export/<str:kind>/<yyyy:year>/<mm:month>',login_required(views.export), name='invoice_export'),
    path("salary_employee/<yyyy:year>/<mm:month>",login_required(views.SalaryEmployeeView.as_view()),name="salary_employee"),
    path('salary_employee/export/<yyyy:year>/<mm:month>',login_required(views.salalyemployee_export), name='salaly_employee_export'),
    path("commission_employee/<yyyy:year>/<mm:month>",login_required(views.CommissionEmployeeView.as_view()),name="commission_employee"),
    path('commission_employee/export/<yyyy:year>/<mm:month>',login_required(views.commissionemployee_export), name='commission_employee_export'),
    path("worktime/<yyyy:year>/<mm:month>",login_required(views.WorktimeView.as_view()),name="worktime"),
    path('worktime/export/<yyyy:year>/<mm:month>',login_required(views.worktime_export), name='worktime_export'),
]

hana/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from django.http import HttpResponse


urlpatterns = [
    #staffs.admin.pyのadmin.site.register(User, MyUserAdmin)もコメントアウト済み
    #path("ad_ksg/", admin.site.urls),
    path("staff/",include("staffs.urls")), 
    path("careuser/",include("careusers.urls")),
    path("service/",include("services.urls")),
    path("schedule/",include("schedules.urls")),
    path("aggregate/",include("aggregates.urls")),
    path("pdf/",include("pdfgen.urls")),
    url(r'^robots.txt$', lambda r: HttpResponse("User-agent: *\nDisallow: /", content_type="text/plain")),
]

aggregates/models.py
from django.db import models
from django.conf import settings

class DataLockdate(models.Model):
     
    lock_date      = models.DateTimeField(verbose_name="データロック最終日時")
    updated_by     = models.ForeignKey(settings.AUTH_USER_MODEL,verbose_name="更新者",on_delete=models.RESTRICT)
    updated_at     = models.DateTimeField(verbose_name="更新日",auto_now=True)

    def __str__(self):
        return f"{self.end_date}"

aggregates/views.py
from schedules.models import Schedule,Report
from aggregates.models import DataLockdate
from schedules.views import search_staff_tr_query
from staffs.models import User
from hana.mixins import StaffUserRequiredMixin,SuperUserRequiredMixin,jpweek
from django.views.generic import TemplateView,ListView,View
from django.http import HttpResponse,Http404,HttpResponseRedirect
from django.utils.timezone import make_aware,localtime
from django.db.models import Q
from django.urls import reverse
import json
import datetime
import calendar
import math
import openpyxl
import re

from dateutil.relativedelta import relativedelta


class TopView(SuperUserRequiredMixin,TemplateView):
    model = Schedule
    template_name = "aggregates/aggregate_top.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        now = make_aware(datetime.datetime.now())
        context['time_now'] = now
        context['month_before'] = now - relativedelta(months=1)

        data_lock_date = DataLockdate.objects.first()
        context['data_lock_date'] = localtime(data_lock_date.lock_date) if data_lock_date else None

        #画面推移後の戻るボタン用にpathをセッションに記録
        self.request.session['from'] = self.request.get_full_path()

        return context

class DataLockView(SuperUserRequiredMixin,View):    
    def get(self,request, **kwargs):
        if not self.request.GET.get('year') or not self.request.GET.get('month'):
            raise Http404
        year = int(self.request.GET.get('year'))
        month= int(self.request.GET.get('month'))
        lock_date = make_aware(datetime.datetime(year,month,1) + relativedelta(months=1) - datetime.timedelta(seconds=1))

        #テーブルを空にする
        DataLockdate.objects.all().delete()
        #追加
        DataLockdate.objects.get_or_create(lock_date=lock_date,updated_by=self.request.user)
        url = reverse('aggregates:aggregate_top')
        return HttpResponseRedirect(url)

class KaigoView(SuperUserRequiredMixin,ListView):
    model = Schedule
    template_name = "aggregates/invoice_kaigo.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        year = self.kwargs.get('year')
        month= self.kwargs.get('month')
        this_month     = make_aware(datetime.datetime(year,month,1))
        this_month_end = this_month + relativedelta(months=1) - datetime.timedelta(seconds=1)
        next_month     = this_month + relativedelta(months=1)
        before_month   = this_month - relativedelta(months=1)

        context['this_month']    = this_month
        context['next_month']    = next_month
        context['before_month']  = before_month

        queryset = Schedule.objects.select_related('report','careuser','service').filter(service__kind=0,report__careuser_confirmed=True,\
                   report__service_in_date__range=[this_month,this_month_end],cancel_flg=False).order_by('careuser__last_kana','careuser__first_kana','report__service_in_date')

        cu = kaigo_list(queryset)        
        context['careuser']  = cu

        return context

def kaigo_export(request,year,month):
    
    if request.user.is_superuser:
        this_month     = make_aware(datetime.datetime(year,month,1))
        this_month_end = this_month + relativedelta(months=1) - datetime.timedelta(seconds=1)

        queryset = Schedule.objects.select_related('report','careuser','service').filter(service__kind=0,report__careuser_confirmed=True,\
                    report__service_in_date__range=[this_month,this_month_end],cancel_flg=False).order_by('careuser__last_kana','careuser__first_kana','report__service_in_date')
        cu_data = kaigo_list(queryset)
        
        json_data =  json.dumps(cu_data,ensure_ascii=False)

        response = HttpResponse(json_data,content_type='application/json')
        response['Content-Disposition'] = 'attachment; filename="kaigo.json"'

        return response
    else:
        return Http404

def kaigo_list(schedules):
    cu={}
    for sche in schedules:
        #careuser毎のリスト作成
        careuser_name = sche.careuser.last_name + " " + sche.careuser.first_name
        if careuser_name not in cu:
            cu[careuser_name]=[]

        s_in_time  = localtime(sche.report.service_in_date)
        s_out_time = localtime(sche.report.service_out_date)

        #スケジュールをサービス内容と日時毎に分類
        service  = sche.service.bill_title
        mix_items = sche.service.mix_items
        night    = False
        midnight = False

        if   s_in_time.time() >= datetime.time(18,00) and s_in_time.time() < datetime.time(22,00):
            night = True
        elif s_in_time.time() >= datetime.time(6,00) and s_in_time.time() < datetime.time(8,00):
            night = True
        elif s_in_time.time() >= datetime.time(0,00) and s_in_time.time() < datetime.time(6,00):
            midnight = True
        elif s_in_time.time() >= datetime.time(22,00) and s_in_time.time() < datetime.time(23,59,59):
            midnight = True
        
        peoples   = sche.peoples
        first     = sche.report.first
        emergency = sche.report.emergency

        in_time  = str(s_in_time.hour).zfill(2) + ":" + str(s_in_time.minute).zfill(2)
        out_time = str(s_out_time.hour).zfill(2) + ":" + str(s_out_time.minute).zfill(2)        

        add_check = False

        #同一のスケジュールがあれば日付を追記
        if cu[careuser_name]:
            for sche in cu[careuser_name]:
                if sche['service'] == service and sche['night']==night and sche['midnight']==midnight and sche['peoples']==peoples and sche['in_time'] == in_time and sche['out_time'] == out_time and sche['first']==first and sche['emergency']==emergency:
                   sche['date'].append(int(s_in_time.day))
                   add_check = True
                   break

        #なければ新たなスケジュールを作成
        if not add_check:
            new_obj = {}
            new_obj['year']      = s_in_time.strftime("%Y")
            new_obj['month']     = s_in_time.strftime("%m")
            new_obj['service']   = service
            new_obj['mix_items'] = mix_items
            new_obj['night']     = night
            new_obj['midnight']  = midnight
            new_obj['peoples']   = peoples
            new_obj['in_time']   = in_time
            new_obj['out_time']  = out_time
            new_obj['date']      = [int(s_in_time.day)]
            new_obj['first']     = first
            new_obj['emergency'] = emergency


            cu[careuser_name].append(new_obj)

    return cu

class SougouView(SuperUserRequiredMixin,ListView):
    model = Schedule
    template_name = "aggregates/invoice_sougou.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        year = self.kwargs.get('year')
        month= self.kwargs.get('month')
        this_month     = make_aware(datetime.datetime(year,month,1))
        this_month_end = this_month + relativedelta(months=1) - datetime.timedelta(seconds=1)
        next_month     = this_month + relativedelta(months=1)
        before_month   = this_month - relativedelta(months=1)

        context['this_month']    = this_month
        context['next_month']    = next_month
        context['before_month']  = before_month

        queryset = Schedule.objects.select_related('report','careuser','service').filter(service__kind=3,report__careuser_confirmed=True,\
                   report__service_in_date__range=[this_month,this_month_end],cancel_flg=False).order_by('careuser__last_kana','careuser__first_kana','report__service_in_date')

        cu = kaigo_list(queryset)        
        context['careuser']  = cu

        return context

def sougou_export(request,year,month):
    
    if request.user.is_superuser:
        this_month     = make_aware(datetime.datetime(year,month,1))
        this_month_end = this_month + relativedelta(months=1) - datetime.timedelta(seconds=1)

        queryset = Schedule.objects.select_related('report','careuser','service').filter(service__kind=3,report__careuser_confirmed=True,\
                    report__service_in_date__range=[this_month,this_month_end],cancel_flg=False).order_by('careuser__last_kana','careuser__first_kana','report__service_in_date')
        
        cu_data = kaigo_list(queryset)        
        json_data =  json.dumps(cu_data,ensure_ascii=False)

        response = HttpResponse(json_data,content_type='application/json')
        response['Content-Disposition'] = 'attachment; filename="sougou.json"'

        return response
    else:
        return Http404

class InvoiceView(SuperUserRequiredMixin,ListView):
    model = Schedule
    template_name = "aggregates/invoice.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        kind = self.kwargs.get('kind')
        context['kind'] = kind
        
        #障害のみ編集
        if kind == "1-0":
            kind = 1
            genre_query = (Q(service__bill_title__contains="身体") | Q(service__bill_title__contains="家事") | Q(service__bill_title__contains="通院"))
        elif kind == "1-1":
            kind = 1
            genre_query = Q(service__bill_title__contains="重度")
        else:
            kind = int(kind)
            genre_query = Q()


        year = self.kwargs.get('year')
        month= self.kwargs.get('month')
        this_month     = make_aware(datetime.datetime(year,month,1))
        this_month_end = this_month + relativedelta(months=1) - datetime.timedelta(seconds=1)
        next_month     = this_month + relativedelta(months=1)
        before_month   = this_month - relativedelta(months=1)

        context['this_month']    = this_month
        context['next_month']    = next_month
        context['before_month']  = before_month

        queryset = Schedule.objects.select_related('report','careuser','service').filter(genre_query,service__kind=kind,report__careuser_confirmed=True,\

templates/aggregates/aggregate_top.html
{% extends "staffs/base.html" %}
{% load static %}
{% load django_bootstrap5 %}
{% load crispy_forms_tags %}
{% load crispy_forms_field %}
{% block extraheader %}
    <link rel="stylesheet" href="{% static 'css/aggregate_top.css' %}?1">
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'js/aggregate_top.js' %}?1"></script>
{% endblock %}
{% block main %}
<div class="container-md">
    <h5 class="mt-5">月次データロック</h5>
    <div class="row mt-4">
        <div class="col-3">現在のロック日時　{{ data_lock_date }}</div>
        <div class="col-9">
            <form method="get" action="{% url 'aggregates:data_lock' %}" name="filter_form" id="data_lock_form">
                <div class="row">
                    <div class="col-2 d-flex justify-content-end p-0"><input type="number" name="year" min="2022" value="{{ month_before.year}}" class="numberinput form-control" id="id_year"></div>
                    <div class="col-1 d-flex justify-content-start align-items-center p-0">年</div>
                    <div class="col-2 d-flex justify-content-end p-0"><input type="number" name="month" min="1" max="12" value="{{ month_before.month}}" class="numberinput form-control" id="id_month"></div>
                    <div class="col-1 d-flex justify-content-start align-items-center p-0">月</div>
                    <div class="col-6 p-0"><button class="btn btn-danger pop_confirm" type="submit">末日までをロックする</button></div>
                </div>
            </form>
        </div> 
    </div>
    <h5 class="mt-5">請求</h5>
    <div class="row mt-4">
        <div class="col-12">
        <a href="{% url 'aggregates:invoice_kaigo'  year=month_before.year month=month_before.month %}"><button class="btn btn-primary kind_btn">介護保険</button></a>
        <a href="{% url 'aggregates:invoice_sougou' year=month_before.year month=month_before.month %}"><button class="btn btn-primary kind_btn">総合事業</button></a>
        <a href="{% url 'aggregates:invoice' kind="1-0" year=month_before.year month=month_before.month %}"><button class="btn btn-primary kind_btn">障害(居宅)</button></a>
        <a href="{% url 'aggregates:invoice' kind="1-1" year=month_before.year month=month_before.month %}"><button class="btn btn-primary kind_btn">障害(重度)</button></a>
        <a href="{% url 'aggregates:invoice' kind="4" year=month_before.year month=month_before.month %}"><button class="btn btn-primary kind_btn">障害(同行援護)</button></a>
        <a href="{% url 'aggregates:invoice' kind="2" year=month_before.year month=month_before.month %}"><button class="btn btn-primary kind_btn">移動支援</button></a>
        <a href="{% url 'aggregates:invoice' kind="5" year=month_before.year month=month_before.month %}"><button class="btn btn-primary kind_btn">自　費</button></a>
    </div>
    <h5 class="mt-5">給与計算</h5>
    <div class="row mt-4">
        <div class="col-2"><a href="{% url 'aggregates:salary_employee' year=month_before.year month=month_before.month %}"><button class="btn btn-primary kind_btn">社員</button></a></div>
        <div class="col-2"><a href="{% url 'aggregates:commission_employee' year=month_before.year month=month_before.month %}"><button class="btn btn-primary kind_btn">登録</button></a></div>
    </div>
    <h5 class="mt-5">勤務時間</h5>
    <div class="col-2 mt-4"><a href="{% url 'aggregates:worktime' year=month_before.year month=month_before.month %}"><button class="btn btn-primary kind_btn">勤務時間</button></a></div>
</div>
{% endblock %}

templates/aggregates/commissionemployee.html
{% extends "staffs/base.html" %}
{% load static %}
{% load humanize %}
{% load django_bootstrap5 %}
{% load crispy_forms_tags %}
{% load crispy_forms_field %}
{% block extraheader %}
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
{% endblock %}
{% block main %}
<div class="container-md">
    <div class="col-4 my-5"><a href="{% url 'aggregates:aggregate_top' %}">{% bootstrap_button button_type="button" content="　戻る　" %}</a></div>
    <h5>歩合給用計算結果</h5>
    <div class="row text-center align-middle mt-5">
        <div class="col-4">
            <a href="{% url 'aggregates:commission_employee' year=before_month.year month=before_month.month %}">{% bootstrap_button button_type="button" button_class="btn-primary month_btn" content="　前月　" %}</a>
        </div>
        <div class="col-4 fs-2">{{this_month.year}}年{{this_month.month}}月</div>
        <div class="col-4">
            <a href="{% url 'aggregates:commission_employee' year=next_month.year month=next_month.month %}">{% bootstrap_button button_type="button" button_class="btn-primary month_btn" content="　翌月　" %}</a>
        </div>
    </div>
    {% if achieve %}
    <div class="col-12 mt-5 text-end"><a href="{% url 'aggregates:commission_employee_export' year=this_month.year month=this_month.month %}" target="_blank">{% bootstrap_button button_type="button" button_class="btn-warning print_btn" content="　出力　" %}</a></div>
    <div class="result_list mt-5">
        {% for staff in achieve %}
            <h5 class="mt-5">{{ staff.staff_name }}</h5>
            {% if staff.month_hour %}
            <div class="row text-center mt-4">
                <div class="col-1 text-light bg-dark">日</div>
                <div class="col-1 text-light bg-dark">合計時間</div>
                <div class="col-8">
                    <div class="row">
                        <div class="col-2 text-start text-light bg-dark">利用者</div>                        
                        <div class="col-1 text-light bg-dark">実施分数</div>
                        <div class="col-3 text-light bg-dark">サービス</div>
                        <div class="col-2 text-light bg-dark">実施時間</div>
                        <div class="col-1 text-light bg-dark">研修</div>
                        <div class="col-1 text-light bg-dark">単価</div>
                        <div class="col-2 text-light bg-dark"></div>
                    </div>
                </div>
                {% if staff.pay_bike%}
                <div class="col-1 text-light bg-dark">日額</div>
                <div class="col-1 text-light bg-dark">バイク代</div>
                {% else %}
                <div class="col-2 text-light bg-dark">日額</div>
                {% endif %}
            </div>
            {% for day,data in staff.days_data.items %}
            {% if data.schedules %}
            <div class="row text-center py-2 border-bottom">                   
                <div class="col-1 d-flex align-items-center justify-content-center border-end">{{day}}日({{data.week}})</div>
                <div class="col-1 d-flex align-items-center justify-content-center">{{ data.day_hour }}時間</div> 
                <div class="col-8">
                    {% for sche in data.schedules %}
                    <div class="row">
                        <div class="col-2 text-start ">{{ sche.careuser }}</div>
                        <div class="col-1{% if sche.check_min %} text-danger{% endif %}">{{ sche.real_minutes }}分</div>
                        <div class="col-3">{{ sche.service }}<span class="{% if sche.check_min %}text-danger{% endif %}">({{sche.service_minutes}}分)</span></div>
                        <div class="col-2">{{ sche.s_in_time }}～{{ sche.s_out_time }}</div>
                        <div class="col-1">{% if sche.kenshuu %}[研修]{% endif %}</div>
                        <div class="col-1">{{ sche.pay|intcomma }}円</div>
                        <div class="col-2"></div>
                    </div>
                    {% if sche.biko %}
                    <div class="row">
                        <div class="col-9 text-start">{{ sche.biko }}</div>
                    </div>
                    {% endif %}
                    {% endfor %}
                </div>
                {% if staff.pay_bike%}
                <div class="col-1 d-flex align-items-center justify-content-center border-start">{{ data.day_pay|intcomma }}円</div>
                <div class="col-1 d-flex align-items-center justify-content-center border-start">{{ data.day_bike_cost|intcomma }}円</div>
                {% else %}
                <div class="col-2 d-flex align-items-center justify-content-center border-start">{{ data.day_pay|intcomma }}円</div>
                {% endif %}
            </div>
            {% endif %}
            {% endfor %}
            {% endif %}
            
            <div class="row text-center mb-5 pt-2">
                <div class="col-1">小計</div>
                <div class="col-1">{{ staff.month_hour }}時間</div>
                <div class="col-8"></div>
                {% if staff.pay_bike%}
                <div class="col-1">{{ staff.month_pay|intcomma }}円</div>
                <div class="col-1">{{ staff.month_bike_cost|intcomma }}円</div>
                {% else %}
                <div class="col-2">{{ staff.month_pay|intcomma }}円</div>
                {% endif %}
            </div>
            <div class="row text-center mb-5 pt-2 fs-4">
                <div class="col-11 text-end">合計</div>
                <div class="col-1 fs-4">{{ staff.month_total_pay|intcomma }}円</div>
            </div>
        {% endfor %}
    </div>
    {% else %}
    <div class="col-12 mt-5 fs-5 text-center">該当者なし</div>
    {% endif %}
</div>
{% endblock %}

templates/aggregates/invoice.html
{% extends "staffs/base.html" %}
{% load static %}
{% load django_bootstrap5 %}
{% load crispy_forms_tags %}
{% load crispy_forms_field %}
{% block extraheader %}
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
{% endblock %}
{% block main %}
<div class="container-md">
    <div class="col-4 my-5"><a href="{% url 'aggregates:aggregate_top' %}">{% bootstrap_button button_type="button" content="　戻る　" %}</a></div>
    <h5>{% if kind == "1-0" %}障害(居宅){% elif kind == "1-1" %}障害(重度){% elif kind == "2" %}移動支援{% elif kind == "4" %}同行援護{% elif kind == "5" %}自費{% endif %}</h5>
    <div class="row text-center align-middle mt-5">
        <div class="col-4">
            <a href="{% url 'aggregates:invoice' kind=kind year=before_month.year month=before_month.month %}">{% bootstrap_button button_type="button" button_class="btn-primary month_btn" content="　前月　" %}</a>
        </div>
        <div class="col-4 fs-2">{{this_month.year}}年{{this_month.month}}月</div>
        <div class="col-4">
            <a href="{% url 'aggregates:invoice' kind=kind year=next_month.year month=next_month.month %}">{% bootstrap_button button_type="button" button_class="btn-primary month_btn" content="　翌月　" %}</a>
        </div>
    </div>
    {% if data %}
    <div class="col-4 my-4"><a href="{% url 'aggregates:invoice_export' kind=kind year=this_month.year month=this_month.month %}"><button class="btn btn-primary">CSVダウンロード</button></a></div>
    <div class="result_list mt-5">
        <div class="row my-4">
            {% for careuser,data in data.items %}
            <div class="row mt-4">
                <div class="col-2">{{ forloop.counter }}　{{ careuser }}</div>
                <div class="col-10">
                    {% for sche in data %}
                    <div class="row">                            
                        <div class="col-4">{{ sche.service }}{% if sche.peoples > 1 %} <{{sche.peoples}}人>{% endif %}{% if sche.first %}<span class="text-danger"> [初回]</span>{% endif %}{% if sche.emergency %}<span class="text-danger"> [緊急]</span>{% endif %}{% if sche.adding %}<span class="text-danger">(合算)</span>{% endif %}</div>
                        <div class="col-1 text-end">{{ sche.in_day }}日</div>
                        <div class="col-2 text-end">{{ sche.in_time }}～{{ sche.out_time }}</div>
                        <div class="col-2">{%if sche.staff1 %}{{sche.staff1}}{% endif %}{%if sche.staff2 %} {{sche.staff2}}{% endif %}{%if sche.staff3 %} {{sche.staff3}}{% endif %}{%if sche.staff4 %} {{sche.staff4}}{% endif %}</div>
                        <div class="col-3">{%if sche.error %}<span class="text-danger">{{sche.error}}</span><br>{% endif %}{%if sche.warnings %}<span class="text-primary">{{sche.warnings}}</span><br>{% endif %}{{sche.biko}}</div>
                    </div>
                    {% endfor %}
                </div>                    
            </div>
            {% endfor %}
        </div>   
    </div>
    {% else %}
    <div class="col-12 mt-5 fs-5 text-center">実績なし</div>
    {% endif %}
</div>
{% endblock %}

templates/aggregates/invoice_kaigo.html
{% extends "staffs/base.html" %}
{% load static %}
{% load django_bootstrap5 %}
{% load crispy_forms_tags %}
{% load crispy_forms_field %}
{% block extraheader %}
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
{% endblock %}
{% block main %}
<div class="container-md">
    <div class="col-4 my-5"><a href="{% url 'aggregates:aggregate_top' %}">{% bootstrap_button button_type="button" content="　戻る　" %}</a></div>
    <h5>介護保険</h5>
    <div class="row text-center align-middle mt-5">
        <div class="col-4">
            <a href="{% url 'aggregates:invoice_kaigo' year=before_month.year month=before_month.month %}">{% bootstrap_button button_type="button" button_class="btn-primary month_btn" content="　前月　" %}</a>
        </div>
        <div class="col-4 fs-2">{{this_month.year}}年{{this_month.month}}月</div>
        <div class="col-4">
            <a href="{% url 'aggregates:invoice_kaigo' year=next_month.year month=next_month.month %}">{% bootstrap_button button_type="button" button_class="btn-primary month_btn" content="　翌月　" %}</a>
        </div>
    </div>
    {% if careuser %}
    <div class="col-4 my-4"><a href="{% url 'aggregates:kaigo_export' year=this_month.year month=this_month.month %}"><button class="btn btn-primary">CSVダウンロード</button></a></div>
    <div class="result_list mt-5">
        {% for cu,sches in careuser.items %}
        <div class="row my-4">
            <div class="col-4">{{ forloop.counter }}　{{cu}}</div>
            <div class="col-8">
            {% for sche in sches %}
                <div class="row">
                    <div class="col-4">{{ sche.service }}{% if sche.night %}(夜){% elif sche.midnight %}(深夜){% endif %}{% if sche.peoples > 1 %} <{{sche.peoples}}人>{% endif %}{% if sche.first %}<span class="text-danger"> [初回]</span>{% endif %}{% if sche.emergency %}<span class="text-danger"> [緊急]</span>{% endif %}</div>
                    <div class="col-4">{{ sche.in_time }} ～ {{ sche.out_time }}</div>
                    <div class="col-4">
                        {% for day in sche.date %}
                            {{ day }}
                        {% endfor %}
                    </div>
                </div>
            {% endfor %}
            </div>
        </div>   
        {% endfor %} 
    </div>
    {% else %}
    <div class="col-12 mt-5 fs-5 text-center">実績なし</div>
    {% endif %}
</div>
{% endblock %}